/* Generated by build/client-wrapper.mjs — do not edit by hand. */
window.__ModuleLoader__.load({
	id: "dsh-env-manager",
	factory: (require) => {
		const module = { exports: {} }
		const exports = module.exports
		Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' })
const React = require("react")
	//#region src/client.ts
	/**
	* 客户端半边 — 在 Settings → Plugins 分区注册「环境变量」页签。
	*
	* 这里是**源码**。DSH 运行时要求客户端插件是**惰性 CJS 工厂**：宿主半边扫到
	* `package.json` 的 `dsh.client` 声明后提供 `/plugins/<id>/client.js`，浏览器端由
	* `window.__ModuleLoader__.load({ id, factory })` 注册工厂，工厂体只在**首次
	* materialize** 时执行。那个形状由 `build/client-wrapper.mjs` 在 tsdown 之后生成，
	* 所以本文件写成普通 ESM 即可。
	*
	* 产物里只允许出现 `require("react")` —— 客户端模块解析顺序是「平台种子表 →
	* 记忆化记录 → boot graph 行 → 已注册工厂」，表外说明符会抛错。因此 `react`
	* 由 tsdown 的 `deps.neverBundle` 保留为外部依赖，见 `tsdown.config.ts`。
	*
	* 数据面：`GET /api/env-manager/state`（见 src/host-api.ts）。
	* 写入面：`POST /api/env-manager/env` 与 `/registry`（见 src/write-routes.ts）。
	* 敏感名的值**永远不会到达浏览器** —— 宿主只回长度。
	*
	* @module dsh-env-manager/client
	*/
	const { useState, useEffect, useCallback } = React;
	const STATE_URL = "/api/env-manager/state";
	const ENV_WRITE_URL = "/api/env-manager/env";
	const ENV_READ_URL = "/api/env-manager/env/read";
	const REGISTRY_URL = "/api/env-manager/registry";
	const CREDENTIAL_WRITE_URL = "/api/env-manager/credentials";
	/**
	* 从 `unknown` 里取可读文案。
	*
	* catch 变量在 `strict` 下是 `unknown`，而原来的写法 `err && err.message ? … : …`
	* 依赖真值判断（空字符串的 message 会退化成 `String(err)`）。这里逐字保留那个
	* 真值语义，只把类型收干净。
	*/
	function messageOf(error) {
		const message = error?.message;
		return String(error && message ? message : error);
	}
	/**
	* 密钥候选名的**下限**。
	*
	* 环境里有很多 `KEY`/`TOKEN`/`SECRET` 形状的名字并不是凭据引用（例如
	* `SSL_CERT_FILE`、`WT_SESSION`）。宿主会对每个候选名调 `describe`，
	* 只有真正已配置或被引用的才需要处理，所以候选集宽一点没有坏处 ——
	* 但绝不能把它们当成"已知密钥"来展示，那会制造噪音。
	*/
	const CREDENTIAL_HINTS = /(^|_)(API_?KEY|KEY|TOKEN|SECRET|PASSWORD|PASSWD|CREDENTIAL)($|_)/i;
	/** 层标识 → 简短标签。 */
	const LAYER_LABEL = {
		process: "启动环境",
		"project-env": "项目 .env",
		"user-env": "$DSH_HOME/.env",
		credential: "凭据库",
		"os-user": "注册表·用户",
		"os-machine": "注册表·系统"
	};
	/** 层标识 → 生效时机说明（设计文档 §11 的档位结论）。 */
	const LAYER_TIMING = {
		process: "🔒 只读",
		"project-env": "🔄 需重启 DSH",
		"user-env": "🔄 需重启 DSH",
		credential: "🟢 立即（DSH 内部）",
		"os-user": "🔄 需重启 DSH",
		"os-machine": "🔄 需重启 DSH"
	};
	/**
	* 可通过 UI 写入的层 → 写路由目标。
	*
	* 显式标注成 `Record<string, …>`：`targetLayer.layer` 是运行期才知道的字符串，
	* 不给索引签名的话每次下标访问都要报隐式 any。
	*/
	const WRITABLE_LAYERS = {
		"project-env": {
			url: ENV_WRITE_URL,
			kind: "env"
		},
		"user-env": {
			url: ENV_WRITE_URL,
			kind: "env"
		},
		"os-user": {
			url: REGISTRY_URL,
			kind: "registry"
		},
		"os-machine": {
			url: REGISTRY_URL,
			kind: "registry"
		}
	};
	const S = {
		wrap: {
			display: "flex",
			flexDirection: "column",
			gap: "12px",
			padding: "12px 0"
		},
		row: {
			display: "flex",
			alignItems: "baseline",
			gap: "8px",
			flexWrap: "wrap"
		},
		head: {
			margin: 0,
			fontSize: "13px",
			fontWeight: 500,
			lineHeight: 1.5
		},
		body: {
			margin: 0,
			fontSize: "12px",
			lineHeight: 1.6,
			opacity: .72
		},
		muted: {
			margin: 0,
			fontSize: "12px",
			lineHeight: 1.6,
			opacity: .55
		},
		mono: {
			fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
			fontSize: "12px"
		},
		card: {
			border: "0.5px solid var(--dsw-alias-border-l2, rgba(128,128,128,0.25))",
			borderRadius: "8px",
			padding: "10px 12px",
			display: "flex",
			flexDirection: "column",
			gap: "6px"
		},
		chip: {
			fontSize: "11px",
			lineHeight: 1.4,
			padding: "1px 6px",
			borderRadius: "4px",
			border: "0.5px solid currentColor",
			opacity: .75
		},
		warn: {
			margin: 0,
			fontSize: "12px",
			lineHeight: 1.6,
			color: "var(--dsw-alias-label-error, #d33)"
		},
		okmsg: {
			margin: 0,
			fontSize: "12px",
			lineHeight: 1.6,
			color: "var(--dsw-alias-label-success, #2a2)"
		},
		button: {
			font: "inherit",
			fontSize: "12px",
			padding: "3px 10px",
			borderRadius: "6px",
			cursor: "pointer",
			border: "0.5px solid var(--dsw-alias-border-l4, rgba(128,128,128,0.4))",
			background: "transparent",
			color: "inherit"
		},
		input: {
			font: "inherit",
			fontSize: "12px",
			padding: "3px 8px",
			borderRadius: "6px",
			border: "0.5px solid var(--dsw-alias-border-l4, rgba(128,128,128,0.4))",
			background: "transparent",
			color: "inherit",
			minWidth: "160px"
		}
	};
	/** 把层里的机器可读码翻译成文案（宿主只传一次文案表）。 */
	const reasonText = (state, code) => state && state.blockedReasonText && state.blockedReasonText[String(code)] || String(code ?? "");
	/**
	* 发起一次写请求。
	*
	* 把 HTTP 层的失败翻译成可读消息：`problems` 数组要逐条展示，
	* 因为那正是"为什么不让写"的答案（禁止名单、有损值等）。
	*/
	async function postJson(url, body) {
		const res = await fetch(url, {
			method: "POST",
			headers: { "content-type": "application/json" },
			body: JSON.stringify(body)
		});
		let parsed;
		try {
			parsed = await res.json();
		} catch {
			throw new Error(`HTTP ${String(res.status)}（响应不是 JSON）`);
		}
		if (res.ok && parsed.ok === true) return parsed;
		const detail = Array.isArray(parsed.problems) && parsed.problems.length > 0 ? parsed.problems.map((p) => (p.name ? p.name + "：" : "") + String(p.message)).join("；") : parsed.message;
		throw new Error(detail || `HTTP ${String(res.status)}`);
	}
	/** 一个变量的摘要行，含就地编辑。 */
	function VariableRow(props) {
		const { variable, state, expanded, onToggle, onSaved } = props;
		const effectiveLayer = variable.layers.find((l) => l.layer === variable.effective);
		const summary = effectiveLayer && effectiveLayer.valueSummary ? effectiveLayer.valueSummary : void 0;
		const [editing, setEditing] = useState(false);
		const [draft, setDraft] = useState("");
		const [busy, setBusy] = useState(false);
		const [error, setError] = useState(null);
		const [saved, setSaved] = useState(null);
		/**
		* 刚删除的注册表值的备份。
		* `null` = 没有待撤销的删除；`'unavailable'` = 删掉了但宿主取不到原值；
		* 对象 = 可用它撤销。
		*/
		const [undo, setUndo] = useState(null);
		/** 可编辑的层：存在、可写、且我们支持它的写路由。 */
		const targetLayer = variable.layers.find((l) => l.writable && WRITABLE_LAYERS[l.layer] !== void 0);
		const beginEdit = useCallback(() => {
			setError(null);
			setSaved(null);
			setDraft(summary && !effectiveLayer?.redacted ? summary.preview : "");
			setEditing(true);
		}, [summary, effectiveLayer]);
		const save = useCallback(async () => {
			if (targetLayer === void 0) return;
			setBusy(true);
			setError(null);
			try {
				const target = WRITABLE_LAYERS[targetLayer.layer];
				if (target.kind === "registry") await postJson(target.url, {
					scope: targetLayer.layer,
					name: variable.name,
					value: draft,
					type: targetLayer.registryType ?? "REG_SZ"
				});
				else {
					const current = await postJson(ENV_READ_URL, { layer: targetLayer.layer });
					await postJson(target.url, {
						layer: targetLayer.layer,
						expectedRevision: current.revision,
						edits: [{
							op: "set",
							name: variable.name,
							value: draft
						}]
					});
				}
				setEditing(false);
				setSaved("已保存");
				if (onSaved) onSaved();
			} catch (err) {
				setError(messageOf(err));
			} finally {
				setBusy(false);
			}
		}, [
			draft,
			targetLayer,
			variable.name,
			onSaved
		]);
		const remove = useCallback(async () => {
			if (targetLayer === void 0) return;
			setBusy(true);
			setError(null);
			setUndo(null);
			try {
				const target = WRITABLE_LAYERS[targetLayer.layer];
				if (target.kind === "registry") {
					const res = await postJson(target.url, {
						scope: targetLayer.layer,
						name: variable.name,
						unset: true
					});
					if (res.undo !== void 0) setUndo({
						scope: targetLayer.layer,
						...res.undo
					});
					else setUndo("unavailable");
				} else {
					const current = await postJson(ENV_READ_URL, { layer: targetLayer.layer });
					await postJson(target.url, {
						layer: targetLayer.layer,
						expectedRevision: current.revision,
						edits: [{
							op: "unset",
							name: variable.name
						}]
					});
				}
				setSaved("已删除");
				if (onSaved) onSaved();
			} catch (err) {
				setError(messageOf(err));
			} finally {
				setBusy(false);
			}
		}, [
			targetLayer,
			variable.name,
			onSaved
		]);
		/** 撤销刚才的注册表删除：把宿主备份的原值与类型写回去。 */
		const undoRemove = useCallback(async () => {
			if (undo === null || undo === "unavailable") return;
			setBusy(true);
			setError(null);
			try {
				await postJson(REGISTRY_URL, {
					scope: undo.scope,
					name: undo.name,
					value: undo.value,
					type: undo.type
				});
				setUndo(null);
				setSaved("已撤销删除");
				if (onSaved) onSaved();
			} catch (err) {
				setError(messageOf(err));
			} finally {
				setBusy(false);
			}
		}, [undo, onSaved]);
		const chips = [];
		if (variable.shadowed) chips.push("被遮蔽 " + String(variable.layerCount) + " 层");
		if (variable.forbidden) chips.push("禁止写入 .env");
		if (variable.runtimeManaged) chips.push("运行时管理");
		if (variable.sensitive) chips.push("shell 不可见");
		const valueText = summary ? summary.preview + (summary.truncated ? "  (" + String(summary.length) + " 字符)" : "") : effectiveLayer && effectiveLayer.redacted ? "(已隐藏，" + String(effectiveLayer.valueLength) + " 字符)" : effectiveLayer && effectiveLayer.valueLength !== void 0 ? "(" + String(effectiveLayer.valueLength) + " 字符)" : "";
		return React.createElement("div", { style: {
			display: "flex",
			flexDirection: "column",
			gap: "2px",
			padding: "3px 0"
		} }, React.createElement("div", { style: S.row }, React.createElement("code", { style: S.mono }, variable.name), React.createElement("span", { style: S.chip }, LAYER_LABEL[variable.effective] || variable.effective || "?"), chips.map((c) => React.createElement("span", {
			key: c,
			style: S.chip
		}, c)), React.createElement("span", { style: {
			...S.body,
			flex: 1,
			minWidth: "80px"
		} }, valueText), targetLayer !== void 0 && !editing ? React.createElement("button", {
			type: "button",
			style: S.button,
			onClick: beginEdit,
			disabled: busy
		}, "编辑") : null, variable.shadowed ? React.createElement("button", {
			type: "button",
			style: S.button,
			onClick: () => onToggle(variable.name)
		}, expanded ? "收起" : "展开各层") : null), editing && targetLayer !== void 0 ? React.createElement("div", { style: {
			...S.row,
			paddingLeft: "12px"
		} }, React.createElement("span", { style: S.muted }, "写入「" + (LAYER_LABEL[targetLayer.layer] || targetLayer.layer) + "」："), React.createElement("input", {
			style: S.input,
			value: draft,
			autoFocus: true,
			onChange: (e) => setDraft(e.target.value)
		}), React.createElement("button", {
			type: "button",
			style: S.button,
			onClick: save,
			disabled: busy
		}, busy ? "保存中…" : "保存"), React.createElement("button", {
			type: "button",
			style: S.button,
			onClick: () => setEditing(false),
			disabled: busy
		}, "取消"), React.createElement("button", {
			type: "button",
			style: S.button,
			onClick: remove,
			disabled: busy
		}, "删除"), React.createElement("span", { style: S.muted }, LAYER_TIMING[targetLayer.layer] || "")) : null, error !== null ? React.createElement("p", { style: {
			...S.warn,
			paddingLeft: "12px"
		} }, "保存失败：" + error) : null, saved !== null ? React.createElement("p", { style: {
			...S.okmsg,
			paddingLeft: "12px"
		} }, saved + "（" + (targetLayer === void 0 ? "" : LAYER_TIMING[targetLayer.layer] || "") + "）") : null, undo === "unavailable" ? React.createElement("p", { style: {
			...S.muted,
			paddingLeft: "12px"
		} }, "已删除；宿主未能取得原值，无法撤销。") : undo !== null ? React.createElement("div", { style: {
			...S.row,
			paddingLeft: "12px"
		} }, React.createElement("span", { style: S.muted }, "已删除（原类型 " + undo.type + "）"), React.createElement("button", {
			type: "button",
			style: S.button,
			onClick: undoRemove,
			disabled: busy
		}, busy ? "恢复中…" : "撤销删除")) : null, expanded ? React.createElement("div", { style: {
			display: "flex",
			flexDirection: "column",
			gap: "2px",
			paddingLeft: "12px"
		} }, variable.layers.map((layer, i) => React.createElement("div", {
			key: String(i),
			style: S.muted
		}, (LAYER_LABEL[layer.layer] || layer.layer) + "：" + (layer.layer === variable.effective ? "【生效】" : "（被遮蔽）") + (layer.writable ? " 可写" : " 不可写") + " " + (LAYER_TIMING[layer.layer] || "") + (layer.registryType ? "  " + layer.registryType : "") + (layer.requiresElevation ? "  需管理员权限" : "") + (layer.blockedCode ? "  — " + reasonText(state, layer.blockedCode) : "") + (layer.path ? "  " + layer.path : "")))) : null);
	}
	/**
	* 密钥面板。
	*
	* 与其他层的关键差别：**宿主永远不回传值**，所以草稿从**空**开始，
	* 界面只能表达"已配置 / 未配置 / 被遮蔽"。这不是 UI 的保守选择，
	* 而是 `dsh-credentials` 的契约（`describe()` 的返回类型没有可以搭载值的
	* 位置）。任何"显示已存密钥"的界面都必然违反该契约。
	*/
	function CredentialPanel(props) {
		const { names, onSaved } = props;
		const [status, setStatus] = useState(null);
		const [available, setAvailable] = useState(true);
		const [error, setError] = useState(null);
		const [editing, setEditing] = useState(null);
		const [draft, setDraft] = useState("");
		const [busy, setBusy] = useState(false);
		const [feedback, setFeedback] = useState(null);
		const key = names.join(",");
		const load = useCallback(() => {
			if (names.length === 0) {
				setStatus({});
				return;
			}
			setError(null);
			fetch("/api/env-manager/credential-state?refs=" + encodeURIComponent(key)).then((res) => res.json()).then((body) => {
				setAvailable(body.available === true);
				setStatus(body.refs || {});
			}).catch((err) => setError(messageOf(err)));
		}, [key, names.length]);
		useEffect(() => {
			load();
		}, [load]);
		const save = useCallback(async () => {
			if (editing === null) return;
			setBusy(true);
			setFeedback(null);
			try {
				await postJson(CREDENTIAL_WRITE_URL, {
					ref: editing,
					value: draft
				});
				setEditing(null);
				setDraft("");
				setFeedback("已保存");
				load();
				if (onSaved) onSaved();
			} catch (err) {
				setFeedback("保存失败：" + messageOf(err));
			} finally {
				setBusy(false);
			}
		}, [
			editing,
			draft,
			load,
			onSaved
		]);
		const remove = useCallback(async () => {
			if (editing === null) return;
			setBusy(true);
			setFeedback(null);
			try {
				await postJson(CREDENTIAL_WRITE_URL, {
					ref: editing,
					unset: true
				});
				setEditing(null);
				setDraft("");
				setFeedback("已删除");
				load();
				if (onSaved) onSaved();
			} catch (err) {
				setFeedback("删除失败：" + messageOf(err));
			} finally {
				setBusy(false);
			}
		}, [
			editing,
			load,
			onSaved
		]);
		if (names.length === 0) return React.createElement("p", { style: S.muted }, "未发现候选的密钥名（环境中没有 KEY/TOKEN/SECRET 形状的变量）。");
		return React.createElement("div", { style: S.card }, React.createElement("p", { style: S.body }, "密钥（" + String(names.length) + " 个候选名）"), React.createElement("p", { style: S.muted }, "宿主**从不回传密钥值**，所以这里只显示\"是否已配置\"。写入后立即对 DSH 内部生效（下一次模型请求即可用），但模型执行的 shell 读不到它 —— 那是有意的安全设计。"), available === false ? React.createElement("p", { style: S.muted }, "本 composition 未挂载凭据域，无法管理密钥。") : null, error !== null ? React.createElement("p", { style: S.warn }, "读取失败：" + error) : null, feedback !== null ? React.createElement("p", { style: S.okmsg }, feedback) : null, status === null ? React.createElement("p", { style: S.muted }, "正在读取密钥状态…") : names.map((name) => {
			const info = status[name] || {
				configured: false,
				editable: false
			};
			return React.createElement("div", {
				key: name,
				style: {
					display: "flex",
					flexDirection: "column",
					gap: "2px",
					padding: "3px 0"
				}
			}, React.createElement("div", { style: S.row }, React.createElement("code", { style: S.mono }, name), React.createElement("span", { style: S.chip }, info.configured ? "已配置" : "未配置"), info.sourceLabel ? React.createElement("span", { style: S.chip }, info.sourceLabel) : null, info.editable ? React.createElement("button", {
				type: "button",
				style: S.button,
				disabled: busy,
				onClick: () => {
					setEditing(name);
					setDraft("");
					setFeedback(null);
				}
			}, info.configured ? "替换" : "设置") : info.blockedReason ? React.createElement("span", { style: S.muted }, info.blockedReason) : null), editing === name ? React.createElement("div", { style: {
				...S.row,
				paddingLeft: "12px"
			} }, React.createElement("input", {
				style: S.input,
				type: "password",
				placeholder: "输入新值（不会回显已存值）",
				value: draft,
				autoFocus: true,
				onChange: (e) => setDraft(e.target.value)
			}), React.createElement("button", {
				type: "button",
				style: S.button,
				onClick: save,
				disabled: busy
			}, busy ? "保存中…" : "保存"), React.createElement("button", {
				type: "button",
				style: S.button,
				onClick: () => {
					setEditing(null);
					setDraft("");
				},
				disabled: busy
			}, "取消"), info.configured ? React.createElement("button", {
				type: "button",
				style: S.button,
				onClick: remove,
				disabled: busy
			}, "删除") : null) : null);
		}));
	}
	/** 页签主体。 */
	function EnvManagerTab() {
		const [state, setState] = useState(null);
		const [error, setError] = useState(null);
		const [loading, setLoading] = useState(true);
		const [expanded, setExpanded] = useState({});
		const [filter, setFilter] = useState("");
		const load = useCallback(() => {
			setLoading(true);
			setError(null);
			fetch(STATE_URL).then((res) => {
				if (!res.ok) throw new Error("HTTP " + String(res.status));
				return res.json();
			}).then((body) => {
				setState(body);
				setLoading(false);
			}).catch((err) => {
				setError(messageOf(err));
				setLoading(false);
			});
		}, []);
		useEffect(() => {
			load();
		}, [load]);
		const toggle = useCallback((name) => {
			setExpanded((prev) => ({
				...prev,
				[name]: !prev[name]
			}));
		}, []);
		if (loading && state === null) return React.createElement("p", { style: S.body }, "正在读取环境…");
		if (error !== null) return React.createElement("div", { style: S.wrap }, React.createElement("p", { style: S.head }, "环境变量管理"), React.createElement("p", { style: S.warn }, "读取失败：" + error), React.createElement("p", { style: S.muted }, "宿主路由：" + STATE_URL + "（需要 DSH 已加载本插件）"), React.createElement("button", {
			type: "button",
			style: S.button,
			onClick: load
		}, "重试"));
		if (state === null) return null;
		const variables = state.variables || [];
		const needle = filter.trim().toUpperCase();
		const shown = needle.length === 0 ? variables : variables.filter((v) => v.name.toUpperCase().includes(needle));
		const groups = [
			{
				key: "runtime",
				title: "运行时 DSH_*（由插件注入，不来自环境）",
				items: shown.filter((v) => v.runtimeManaged)
			},
			{
				key: "shadowed",
				title: "多层竞争（同名变量存在于多个权威层）",
				items: shown.filter((v) => v.shadowed && !v.runtimeManaged)
			},
			{
				key: "plain",
				title: "单层变量",
				items: shown.filter((v) => !v.shadowed && !v.runtimeManaged)
			}
		];
		const credentialNames = variables.filter((v) => CREDENTIAL_HINTS.test(v.name)).map((v) => v.name).sort();
		return React.createElement("div", { style: S.wrap }, React.createElement("p", { style: S.head }, "环境变量管理"), React.createElement("p", { style: S.muted }, "工作目录 " + state.cwd + "　·　home " + state.home + "　·　共 " + String(state.counts.total) + " 项" + (state.counts.shadowed > 0 ? "（" + String(state.counts.shadowed) + " 项多层竞争）" : "")), React.createElement("p", { style: S.muted }, "项目 .env：" + (state.files.project || "（不存在）") + "　·　用户 .env：" + (state.files.user || "（不存在）")), state.os ? React.createElement("p", { style: S.muted }, state.os.skipped === true ? "OS 环境层：本次请求已跳过（os=0）" : state.os.supported === false ? "OS 环境层：当前平台不支持读写（Linux/macOS 没有单一可靠的写入点，见设计文档 §2）" : "OS 环境层：注册表·用户 " + String(state.os.scopes?.["os-user"]?.count ?? 0) + " 项" + (state.os.scopes?.["os-user"]?.error ? "（读取失败：" + state.os.scopes["os-user"].error + "）" : "") + "　·　注册表·系统 " + String(state.os.scopes?.["os-machine"]?.count ?? 0) + " 项" + (state.os.scopes?.["os-machine"]?.error ? "（读取失败：" + state.os.scopes["os-machine"].error + "）" : "")) : null, (state.warnings ?? []).map((w, i) => React.createElement("p", {
			key: String(i),
			style: S.warn
		}, "⚠ " + (w.path ? w.path + "：" : "") + (w.message || w.code))), React.createElement("div", { style: S.row }, React.createElement("input", {
			style: S.input,
			placeholder: "按名称过滤…",
			value: filter,
			onChange: (e) => setFilter(e.target.value)
		}), React.createElement("button", {
			type: "button",
			style: S.button,
			onClick: load
		}, "刷新")), groups.map((group) => group.items.length === 0 ? null : React.createElement("div", {
			key: group.key,
			style: S.card
		}, React.createElement("p", { style: S.body }, group.title + "（" + String(group.items.length) + "）"), group.items.slice(0, 40).map((v) => React.createElement(VariableRow, {
			key: v.name,
			variable: v,
			state,
			expanded: expanded[v.name] === true,
			onToggle: toggle,
			onSaved: load
		})), group.items.length > 40 ? React.createElement("p", { style: S.muted }, "另有 " + String(group.items.length - 40) + " 项，请用过滤框缩小范围") : null)), React.createElement(CredentialPanel, {
			names: credentialNames,
			onSaved: load
		}), React.createElement("p", { style: S.muted }, "说明：标记为「shell 不可见」的名字会被子进程清洗（/KEY|PASSWORD|SECRET|TOKEN/i），所以模型执行的命令读不到它们 —— 这是「仅 DSH 内部可用」的密钥。"), React.createElement("p", { style: S.muted }, "说明：注册表层的改动在 DSH 重启前**不会改变生效值** —— 注册表的值在启动时已被继承进「启动环境」，而它的优先级更高。展开被遮蔽的多层变量即可看到这种竞争。"), React.createElement("p", { style: S.muted }, "说明：写入 .env 使用「读取 revision → 带栅栏写入」的乐观并发；若期间文件被其他程序改动，保存会被拒绝而不会覆盖对方的改动。"));
	}
	/**
	* 本插件依赖的 cordis 服务（**浏览器侧的 fiber inject**）。
	*
	* 这是 `cannot get property "slots" without inject` 检查的那个 inject。
	*
	* 两次修错的过程记在这里，免得重犯：
	*
	*   1. 改 `package.json` 的 `dsh.client.inject`（列包名）→ **无效**。
	*      那是 `dsh-client-modules` 的组合机制，只管 boot graph 的加载顺序，
	*      不解除 cordis 的服务访问限制。
	*   2. 我以为客户端 bundle 必须"return 插件对象"→ 也没解决。
	*
	* 真正的依据在 cordis 与第一方产物里：
	*   - cordis registry：`new Fiber(this.ctx, config, Inject.resolve(plugin.inject), …)`
	*     —— 它读的是**传进 ctx.plugin() 的那个对象**的 `inject`
	*   - 客户端 runner 传的是 materialize 出的 `module.exports`
	*   - 第一方产物结尾就是 `exports.apply = apply; exports.inject = inject;`
	*     （如 `dsh-client-ui-goal`）
	*
	* 所以：**具名导出 `inject`（服务名数组）+ 具名导出 `apply`**，与第一方一致。
	* 服务名只有 `"slots"`；槽位就绪由 `slots.inject()` 自己处理。
	*/
	const inject = ["slots"];
	/**
	* 载入客户端插件。
	*
	* `ctx` 只声明**用到的**那一小块（`slots.inject` / `slots.register`）：
	* 客户端 runner 传进来的是它自己的 cordis 上下文，本包不该、也无法完整声明它。
	* 真正要保证的是 `inject = ['slots']` 已导出 —— 没有它，cordis 会以
	* `cannot get property "slots" without inject` 直接拒绝装载。
	*
	* @param ctx - 客户端 cordis 上下文（已因 `inject` 而保证 `ctx.slots` 可用）。
	*/
	function apply(ctx) {
		ctx.slots.inject("settings.plugins.tab", () => ctx.slots.register({
			name: "settings.plugins.tab",
			id: "env-manager",
			order: 100,
			label: "环境变量"
		}, EnvManagerTab));
	}
	//#endregion

	exports.EnvManagerTab = EnvManagerTab;
	exports.apply = apply;
	exports.inject = inject;
	return module.exports
	}
})
