/* Generated by build/client-wrapper.mjs — do not edit by hand. */
window.__ModuleLoader__.load({
	id: "dsh-env-manager",
	factory: (require) => {
		const module = { exports: {} }
		const exports = module.exports
		Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' })
const React = require("react")
const { Button, DisclosureRow, IconChevronDownOutline14, IconContextInjectionOutline16, IconEditOutline16, IconRefreshOutline16, IconSearchOutline16, IconTrashOutline16, Input, Modal, Switch } = require("@deepseek-ai/dsh-client-ui-primitives")
	//#region src/client-ui.ts
	/**
	* 客户端页签的**表现层**。
	*
	* 与 `client.ts` 的分工：这里只有排版与样式，不认识 `fetch`、也不持有状态；
	* `client.ts` 负责数据流并把结果交给这里的组件。
	*
	* ── 排版原则（这一层的全部理由）────────────────────────────────────────────
	*
	* 「环境变量」这个界面的**内容就是 KEY 与 VALUE**。其余一切都是注解：
	* 生效层、层数、遮蔽、生效时机、平台限制。所以：
	*
	*   1. **KEY / VALUE 占满宽度。** 一行就是 `KEY  VALUE  · 次要信息`，
	*      等宽字体 + 三列对齐，让上百行能像 `env` 输出那样竖着扫下来。
	*   2. **次要信息一律 11px / 低对比。** 不用彩色胶囊、不用边框卡片 ——
	*      胶囊和边框会把注解抬到和内容一样的视觉重量，这是原版"丑"的主因。
	*      次要信息用 `·` 串成一行跟在后面，读得到但抢不走注意力。
	*   3. **操作按需出现。** 编辑/展开是图标按钮，只在悬停该行或键盘落在行内时
	*      出现。密集列表里常驻按钮会让每一行都变成一条按钮条。
	*   4. **分组用一条细横线 + 小字标题**，不要卡片盒子。盒子会切断竖向扫描。
	*   5. **颜色只用于状态**，不用于装饰。正文颜色全部继承
	*      `--dsw-alias-*`（DSH 自己的语义色），所以明暗主题自动正确。
	*
	* 需要 `:hover` / `:focus-within` 的部分走一张注入的极小样式表 —— 内联
	* style 表达不了伪类，而引入 CSS 工具链只为一个悬停态不值得。
	*
	* @module dsh-env-manager/client-ui
	*/
	/** 等宽字体栈：KEY / VALUE / 路径都用它。 */
	const MONO = "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace";
	/**
	* 字号与不透明度只在这里定义一次。
	*
	* 三档就够：内容（KEY/VALUE）、注解（meta）、结构（分组标题）。
	* 原版的问题是每一类信息都自带一套字号 + 边框 + 颜色，于是没有主次。
	*/
	const T = {
		/** KEY：内容，最高对比、略加粗。 */
		key: {
			fontSize: "12.5px",
			fontWeight: 560,
			letterSpacing: 0
		},
		/** VALUE：内容，等宽、稍低对比（长值要能一眼看出边界）。 */
		value: {
			fontSize: "12.5px",
			fontWeight: 400,
			opacity: .74
		},
		/** 注解：生效层、层数、字符数、时机。 */
		meta: {
			fontSize: "11px",
			fontWeight: 400,
			opacity: .42
		},
		/** 展开后的每层细节。 */
		detail: {
			fontSize: "11.5px",
			fontWeight: 400,
			opacity: .5
		},
		/** 分组标题。 */
		group: {
			fontSize: "11px",
			fontWeight: 520,
			letterSpacing: "0.06em",
			opacity: .5
		}
	};
	/** 注入一次的小样式表：只放内联 style 表达不了的伪类与媒体查询。 */
	const STYLE_ID = "dsh-env-manager-client-style";
	/**
	* 这张表负责三件内联样式做不到的事：
	*
	* 1. **`:hover` / `:focus-within`** —— 行尾操作按需出现；
	* 2. **响应式** —— 窄屏把三列压成两列，VALUE 换到第二行；
	* 3. **模态框宽度** —— 内容就是 KEY/VALUE，横向越宽越好扫，所以显式放宽到
	*    1080px（`Modal` 自带的默认宽度对这张表偏窄）。能覆盖它是因为两边都是
	*    单类选择器，同优先级下**后出现在文档里的胜出**，而这张表是运行时追加到
	*    `<head>` 末尾的。
	*/
	const CSS = `
	.dsh-envmgr-dialog { width: min(1080px, calc(100vw - 48px)); max-width: none; }
	.dsh-envmgr-row {
	  display: grid;
	  grid-template-columns: minmax(140px, 260px) minmax(0, 1fr) auto;
	  align-items: baseline;
	  column-gap: 12px;
	  padding: 5px 8px;
	  border-radius: 6px;
	}
	.dsh-envmgr-row:hover { background: var(--dsw-alias-fill-quaternary, rgba(128,128,128,0.10)); }
	.dsh-envmgr-actions { opacity: 0; transition: opacity .12s ease; }
	.dsh-envmgr-row:hover .dsh-envmgr-actions,
	.dsh-envmgr-row:focus-within .dsh-envmgr-actions { opacity: 1; }
	@media (hover: none) { .dsh-envmgr-actions { opacity: 1; } }
	.dsh-envmgr-scroll { max-height: min(62vh, 760px); overflow-y: auto; overscroll-behavior: contain; }
	.dsh-envmgr-valuecell { min-width: 0; }
	.dsh-envmgr-valuecell:hover { text-decoration: underline; text-decoration-style: dotted; text-underline-offset: 2px; }

	/* 窄屏：KEY 与注解一行，VALUE 独占下一行 —— 竖着扫仍然成立，且不再横向溢出 */
	@media (max-width: 760px) {
	  .dsh-envmgr-dialog { width: calc(100vw - 16px); }
	  .dsh-envmgr-row { grid-template-columns: minmax(0, 1fr) auto; row-gap: 2px; }
	  .dsh-envmgr-valuecell { grid-column: 1 / -1; }
	}
	`;
	/**
	* 把上面那张样式表挂进 document（幂等）。
	*
	* 在模块体里调用 —— 客户端 bundle 是惰性 CJS 工厂，工厂体只在首次
	* materialize 时执行，所以挂载前不会有副作用。
	*/
	function installClientStyles() {
		if (typeof document === "undefined") return;
		if (document.getElementById(STYLE_ID) !== null) return;
		const style = document.createElement("style");
		style.id = STYLE_ID;
		style.textContent = CSS;
		document.head.appendChild(style);
	}
	/**
	* 一行。三列网格：KEY 定宽、VALUE 占满、注解靠右。
	*
	* 网格定义在样式表里而不是内联：窄屏要换成两列，而媒体查询赢不过内联样式。
	* KEY 用 `minmax(140px, 260px)`：短名字不浪费空间，遇到
	* `HUOSHAN_DOUBAO_ACCESS_TOKEN` 这种长名字也不会把 VALUE 挤没。
	*/
	function Row(props) {
		return React.createElement("div", {
			className: "dsh-envmgr-row",
			style: { background: props.active === true ? "var(--dsw-alias-fill-quaternary, rgba(128,128,128,0.10))" : "transparent" }
		}, props.children);
	}
	/** 行尾的操作图标簇：默认透明，悬停整行时出现。 */
	function RowActions(props) {
		return React.createElement("span", {
			className: "dsh-envmgr-actions",
			style: {
				display: "inline-flex",
				alignItems: "center",
				gap: "2px"
			}
		}, props.children);
	}
	/** KEY：内容的主角之一。等宽、高对比、溢出省略。 */
	function Key(props) {
		return React.createElement("span", {
			style: {
				...T.key,
				fontFamily: MONO,
				overflow: "hidden",
				textOverflow: "ellipsis",
				whiteSpace: "nowrap"
			},
			...props.title === void 0 ? {} : { title: props.title }
		}, props.children);
	}
	/**
	* VALUE：另一个主角。等宽、可省略。
	*
	* `masked` 用点阵表示"宿主不回传这个值" —— 这比空白更能说明状态。
	* 两类情况会走到这里：凭据域（契约上根本没有值可给），以及用户没有打开
	* 「显示敏感值」时宿主按名字屏蔽的值（见设计文档 §33）。
	*/
	function Value(props) {
		return React.createElement("span", {
			className: "dsh-envmgr-valuecell",
			style: {
				...T.value,
				fontFamily: MONO,
				overflow: "hidden",
				textOverflow: "ellipsis",
				whiteSpace: "nowrap",
				...props.onClick === void 0 ? {} : { cursor: "pointer" }
			},
			...props.title === void 0 ? {} : { title: props.title },
			...props.onClick === void 0 ? {} : { onClick: props.onClick }
		}, props.masked === true ? "••••••••••" : props.children);
	}
	/** 注解：一行里跟在 VALUE 后面的全部次要信息，用 `·` 连接。 */
	function Meta(props) {
		const text = props.parts.filter((p) => typeof p === "string" && p.length > 0).join(" · ");
		if (text.length === 0) return null;
		return React.createElement("span", { style: {
			...T.meta,
			whiteSpace: "nowrap"
		} }, text);
	}
	/** 分组标题：小字 + 一条细横线 + 计数。横向规则把视线按组切开。 */
	function GroupHeading(props) {
		return React.createElement("div", { style: {
			display: "flex",
			alignItems: "center",
			gap: "8px",
			margin: "14px 0 2px",
			padding: "0 8px"
		} }, React.createElement("span", { style: T.group }, props.title), React.createElement("span", { style: {
			flex: 1,
			height: "1px",
			background: "currentColor",
			opacity: .12
		} }), props.count === void 0 ? null : React.createElement("span", { style: {
			...T.meta,
			fontVariantNumeric: "tabular-nums"
		} }, String(props.count)));
	}
	/**
	* 展开后的每层细节。
	*
	* 用左侧一条细竖线表示"从属于上面那一行"，而不是再套一个盒子 ——
	* 盒子会让人以为它是一个独立条目。层名与事实分成两列，便于竖向比对。
	*/
	function LayerDetail(props) {
		return React.createElement("div", { style: {
			margin: "1px 0 4px 8px",
			paddingLeft: "11px",
			borderLeft: "1px solid var(--dsw-alias-border-l2, rgba(128,128,128,0.22))",
			display: "grid",
			gridTemplateColumns: "auto minmax(0, 1fr)",
			columnGap: "10px",
			rowGap: "1px"
		} }, props.rows.flatMap((row, i) => [React.createElement("span", {
			key: `n${String(i)}`,
			style: {
				...T.detail,
				whiteSpace: "nowrap"
			}
		}, row.name), React.createElement("span", {
			key: `f${String(i)}`,
			style: {
				...T.detail,
				fontFamily: MONO
			}
		}, row.facts)]));
	}
	/** 可滚动的列表容器：固定工具条与脚注，只让内容滚。 */
	function ScrollArea(props) {
		return React.createElement("div", {
			className: "dsh-envmgr-scroll",
			style: {
				margin: "0 -4px",
				padding: "0 4px"
			}
		}, props.children);
	}
	/** 工具条：搜索 + 刷新 + 计数。固定在列表上方，不参与滚动。 */
	function Toolbar(props) {
		return React.createElement("div", { style: {
			display: "flex",
			alignItems: "center",
			gap: "8px",
			marginBottom: "2px"
		} }, props.children);
	}
	/** 空状态：一句低对比说明，不要插图也不要按钮。 */
	function Empty(props) {
		return React.createElement("p", { style: {
			...T.meta,
			margin: "18px 8px",
			textAlign: "center"
		} }, props.children);
	}
	/** 脚注里的一行说明。 */
	function Note(props) {
		return React.createElement("p", { style: {
			...T.detail,
			margin: "4px 0",
			lineHeight: 1.7
		} }, props.children);
	}
	/** 加载/错误这类整屏状态。 */
	function Placeholder(props) {
		return React.createElement("p", { style: {
			...T.detail,
			margin: "24px 8px",
			textAlign: "center",
			opacity: props.tone === "warn" ? .8 : .5
		} }, props.children);
	}
	//#endregion
	//#region src/client.ts
	/**
	* 客户端半边 — 在 Settings → Plugins 分区注册「环境变量」页签。
	*
	* 这里是**源码**。DSH 运行时要求客户端插件是**惰性 CJS 工厂**：宿主半边扫到
	* `package.json` 的 `dsh.client` 声明后提供 `/plugins/<id>/client.js`，浏览器端由
	* `window.__ModuleLoader__.load({ id, factory })` 注册工厂，工厂体只在**首次
	* materialize** 时执行。那个形状由 `build/client-wrapper.mjs` 在 tsdown 之后生成，
	* 所以本文件写成普通 ESM 即可。
	*
	* 产物里只允许出现 `require("react")` —— 客户端模块解析顺序是「平台种子表 →
	* 记忆化记录 → boot graph 行 → 已注册工厂」，表外说明符会抛错。因此 `react`
	* 由 tsdown 的 `deps.neverBundle` 保留为外部依赖，见 `tsdown.config.ts`。
	*
	* 数据面：`GET /api/env-manager/state`（见 src/host-api.ts）。
	* 写入面：`POST /api/env-manager/env` 与 `/registry`（见 src/write-routes.ts）。
	* 敏感名的值**永远不会到达浏览器** —— 宿主只回长度。
	*
	* @module dsh-env-manager/client
	*/
	const { useState, useEffect, useCallback } = React;
	const STATE_URL = "/api/env-manager/state";
	const ENV_WRITE_URL = "/api/env-manager/env";
	const ENV_READ_URL = "/api/env-manager/env/read";
	const REGISTRY_URL = "/api/env-manager/registry";
	const CREDENTIAL_WRITE_URL = "/api/env-manager/credentials";
	/**
	* 从 `unknown` 里取可读文案。
	*
	* catch 变量在 `strict` 下是 `unknown`，而原来的写法 `err && err.message ? … : …`
	* 依赖真值判断（空字符串的 message 会退化成 `String(err)`）。这里逐字保留那个
	* 真值语义，只把类型收干净。
	*/
	function messageOf(error) {
		const message = error?.message;
		return String(error && message ? message : error);
	}
	/**
	* 密钥候选名的**下限**。
	*
	* 环境里有很多 `KEY`/`TOKEN`/`SECRET` 形状的名字并不是凭据引用（例如
	* `SSL_CERT_FILE`、`WT_SESSION`）。宿主会对每个候选名调 `describe`，
	* 只有真正已配置或被引用的才需要处理，所以候选集宽一点没有坏处 ——
	* 但绝不能把它们当成"已知密钥"来展示，那会制造噪音。
	*/
	const CREDENTIAL_HINTS = /(^|_)(API_?KEY|KEY|TOKEN|SECRET|PASSWORD|PASSWD|CREDENTIAL)($|_)/i;
	/** 层标识 → 简短标签。 */
	const LAYER_LABEL = {
		process: "启动环境",
		"project-env": "项目 .env",
		"user-env": "$DSH_HOME/.env",
		credential: "凭据库",
		"os-user": "注册表·用户",
		"os-machine": "注册表·系统"
	};
	/** 层标识 → 生效时机说明（设计文档 §11 的档位结论）。 */
	const LAYER_TIMING = {
		process: "🔒 只读",
		"project-env": "🔄 需重启 DSH",
		"user-env": "🔄 需重启 DSH",
		credential: "🟢 立即（DSH 内部）",
		"os-user": "🔄 需重启 DSH",
		"os-machine": "🔄 需重启 DSH"
	};
	/**
	* 可通过 UI 写入的层 → 写路由目标。
	*
	* 显式标注成 `Record<string, …>`：`targetLayer.layer` 是运行期才知道的字符串，
	* 不给索引签名的话每次下标访问都要报隐式 any。
	*/
	const WRITABLE_LAYERS = {
		"project-env": {
			url: ENV_WRITE_URL,
			kind: "env"
		},
		"user-env": {
			url: ENV_WRITE_URL,
			kind: "env"
		},
		"os-user": {
			url: REGISTRY_URL,
			kind: "registry"
		},
		"os-machine": {
			url: REGISTRY_URL,
			kind: "registry"
		}
	};
	/** 把层里的机器可读码翻译成文案（宿主只传一次文案表）。 */
	const reasonText = (state, code) => state && state.blockedReasonText && state.blockedReasonText[String(code)] || String(code ?? "");
	/**
	* 发起一次写请求。
	*
	* 把 HTTP 层的失败翻译成可读消息：`problems` 数组要逐条展示，
	* 因为那正是"为什么不让写"的答案（禁止名单、有损值等）。
	*/
	async function postJson(url, body) {
		const res = await fetch(url, {
			method: "POST",
			headers: { "content-type": "application/json" },
			body: JSON.stringify(body)
		});
		let parsed;
		try {
			parsed = await res.json();
		} catch {
			throw new Error(`HTTP ${String(res.status)}（响应不是 JSON）`);
		}
		if (res.ok && parsed.ok === true) return parsed;
		const detail = Array.isArray(parsed.problems) && parsed.problems.length > 0 ? parsed.problems.map((p) => (p.name ? p.name + "：" : "") + String(p.message)).join("；") : parsed.message;
		throw new Error(detail || `HTTP ${String(res.status)}`);
	}
	/** 一个变量的摘要行，含就地编辑。 */
	function VariableRow(props) {
		const { variable, state, expanded, onToggle, onSaved, revealSecrets } = props;
		const effectiveLayer = variable.layers.find((l) => l.layer === variable.effective);
		const summary = effectiveLayer && effectiveLayer.valueSummary ? effectiveLayer.valueSummary : void 0;
		const [editing, setEditing] = useState(false);
		const [draft, setDraft] = useState("");
		const [busy, setBusy] = useState(false);
		const [error, setError] = useState(null);
		const [saved, setSaved] = useState(null);
		/**
		* 刚删除的注册表值的备份。
		* `null` = 没有待撤销的删除；`'unavailable'` = 删掉了但宿主取不到原值；
		* 对象 = 可用它撤销。
		*/
		const [undo, setUndo] = useState(null);
		/** 可编辑的层：存在、可写、且我们支持它的写路由。 */
		const targetLayer = variable.layers.find((l) => l.writable && WRITABLE_LAYERS[l.layer] !== void 0);
		const beginEdit = useCallback(() => {
			setError(null);
			setSaved(null);
			setDraft(summary && !effectiveLayer?.redacted ? summary.preview : "");
			setEditing(true);
		}, [summary, effectiveLayer]);
		const save = useCallback(async () => {
			if (targetLayer === void 0) return;
			setBusy(true);
			setError(null);
			try {
				const target = WRITABLE_LAYERS[targetLayer.layer];
				if (target.kind === "registry") await postJson(target.url, {
					scope: targetLayer.layer,
					name: variable.name,
					value: draft,
					type: targetLayer.registryType ?? "REG_SZ"
				});
				else {
					const current = await postJson(ENV_READ_URL, { layer: targetLayer.layer });
					await postJson(target.url, {
						layer: targetLayer.layer,
						expectedRevision: current.revision,
						edits: [{
							op: "set",
							name: variable.name,
							value: draft
						}]
					});
				}
				setEditing(false);
				setSaved("已保存");
				if (onSaved) onSaved();
			} catch (err) {
				setError(messageOf(err));
			} finally {
				setBusy(false);
			}
		}, [
			draft,
			targetLayer,
			variable.name,
			onSaved
		]);
		const remove = useCallback(async () => {
			if (targetLayer === void 0) return;
			setBusy(true);
			setError(null);
			setUndo(null);
			try {
				const target = WRITABLE_LAYERS[targetLayer.layer];
				if (target.kind === "registry") {
					const res = await postJson(target.url, {
						scope: targetLayer.layer,
						name: variable.name,
						unset: true
					});
					if (res.undo !== void 0) setUndo({
						scope: targetLayer.layer,
						...res.undo
					});
					else setUndo("unavailable");
				} else {
					const current = await postJson(ENV_READ_URL, { layer: targetLayer.layer });
					await postJson(target.url, {
						layer: targetLayer.layer,
						expectedRevision: current.revision,
						edits: [{
							op: "unset",
							name: variable.name
						}]
					});
				}
				setSaved("已删除");
				if (onSaved) onSaved();
			} catch (err) {
				setError(messageOf(err));
			} finally {
				setBusy(false);
			}
		}, [
			targetLayer,
			variable.name,
			onSaved
		]);
		/** 撤销刚才的注册表删除：把宿主备份的原值与类型写回去。 */
		const undoRemove = useCallback(async () => {
			if (undo === null || undo === "unavailable") return;
			setBusy(true);
			setError(null);
			try {
				await postJson(REGISTRY_URL, {
					scope: undo.scope,
					name: undo.name,
					value: undo.value,
					type: undo.type
				});
				setUndo(null);
				setSaved("已撤销删除");
				if (onSaved) onSaved();
			} catch (err) {
				setError(messageOf(err));
			} finally {
				setBusy(false);
			}
		}, [undo, onSaved]);
		const hidden = summary === void 0 && effectiveLayer?.redacted === true;
		const lengthHint = summary !== void 0 && summary.truncated === true ? `${String(summary.length)} 字符` : hidden ? `${String(effectiveLayer?.valueLength ?? 0)} 字符` : null;
		const meta = React.createElement(Meta, { parts: [
			LAYER_LABEL[variable.effective] ?? variable.effective ?? "?",
			variable.shadowed === true ? `遮蔽 ${String(variable.layerCount ?? variable.layers.length)} 层` : null,
			variable.sensitive === true ? "shell 不可见" : null,
			variable.forbidden === true ? "禁止写入 .env" : null,
			lengthHint
		] });
		const valueText = summary !== void 0 ? summary.preview : hidden ? null : effectiveLayer?.valueLength !== void 0 ? `(${String(effectiveLayer.valueLength)} 字符)` : null;
		/**
		* 被屏蔽时，提示要**说清是谁屏蔽的** —— 这两种情况的可行动作完全不同：
		*
		*   - 名字像密钥、开关没开 → 是**本界面**没要，打开开关就能看到（可行动）；
		*   - 开关已开却还是空 → 宿主没有回传。凭据域在契约上就没有值可给（不可行动），
		*     这时不该诱导用户去点开关。
		*/
		const maskTitle = !hidden ? void 0 : revealSecrets === true ? "宿主没有回传这个值（凭据域在契约上只提供\"是否已配置\"）" : "名字像密钥，默认不取回值；打开工具条里的「显示敏感值」即可查看";
		const value = React.createElement(Value, {
			masked: hidden,
			title: summary === void 0 ? maskTitle : `${summary.preview}${summary.truncated === true ? ` …（共 ${String(summary.length)} 字符）` : ""}`,
			children: valueText
		});
		const rowActions = React.createElement(RowActions, null, targetLayer === void 0 || editing ? null : React.createElement(Button, {
			variant: "ghost",
			size: "sm",
			icon: React.createElement(IconEditOutline16, null),
			title: "编辑这一项",
			"aria-label": "编辑",
			disabled: busy,
			onClick: beginEdit
		}), variable.shadowed === true ? React.createElement(Button, {
			variant: "ghost",
			size: "sm",
			icon: React.createElement(IconChevronDownOutline14, null),
			title: expanded ? "收起各层" : "展开各层",
			"aria-label": expanded ? "收起各层" : "展开各层",
			onClick: () => onToggle(variable.name)
		}) : null);
		return React.createElement("div", { style: { paddingBottom: "1px" } }, React.createElement(Row, { active: editing || expanded }, React.createElement(Key, { title: variable.name }, variable.name), value, React.createElement("span", { style: {
			display: "inline-flex",
			alignItems: "baseline",
			gap: "8px"
		} }, meta, rowActions)), editing && targetLayer !== void 0 ? React.createElement("div", { style: {
			display: "flex",
			alignItems: "center",
			gap: "6px",
			padding: "2px 8px 6px"
		} }, React.createElement("span", { style: {
			...T.meta,
			whiteSpace: "nowrap"
		} }, `写入「${LAYER_LABEL[targetLayer.layer] ?? targetLayer.layer}」`), React.createElement(Input, {
			value: draft,
			autoFocus: true,
			placeholder: "新值",
			style: {
				flex: 1,
				fontFamily: MONO,
				fontSize: "12px"
			},
			onChange: (e) => setDraft(e.target.value)
		}), React.createElement(Button, {
			variant: "outline",
			size: "sm",
			disabled: busy,
			onClick: save
		}, busy ? "保存中" : "保存"), React.createElement(Button, {
			variant: "ghost",
			size: "sm",
			disabled: busy,
			onClick: () => setEditing(false)
		}, "取消"), React.createElement(Button, {
			variant: "ghost",
			size: "sm",
			icon: React.createElement(IconTrashOutline16, null),
			title: "删除这一项",
			"aria-label": "删除",
			disabled: busy,
			onClick: remove
		}), React.createElement("span", { style: {
			...T.meta,
			whiteSpace: "nowrap"
		} }, LAYER_TIMING[targetLayer.layer] ?? "")) : null, error !== null ? React.createElement(Note, null, `保存失败：${error}`) : null, saved !== null ? React.createElement(Note, null, `${saved}${targetLayer === void 0 ? "" : `（${LAYER_TIMING[targetLayer.layer] ?? ""}）`}`) : null, undo === "unavailable" ? React.createElement(Note, null, "已删除；宿主未能取得原值，无法撤销。") : undo !== null ? React.createElement("div", { style: {
			display: "flex",
			alignItems: "center",
			gap: "8px",
			padding: "0 8px 4px"
		} }, React.createElement("span", { style: T.meta }, `已删除（原类型 ${undo.type}）`), React.createElement(Button, {
			variant: "ghost",
			size: "sm",
			disabled: busy,
			onClick: undoRemove
		}, busy ? "恢复中" : "撤销删除")) : null, expanded ? React.createElement(LayerDetail, { rows: variable.layers.map((layer) => ({
			name: LAYER_LABEL[layer.layer] ?? layer.layer,
			facts: [
				layer.layer === variable.effective ? "【生效】" : "（被遮蔽）",
				layer.writable === true ? "可写" : "不可写",
				LAYER_TIMING[layer.layer] ?? "",
				layer.registryType ?? "",
				layer.requiresElevation === true ? "需管理员权限" : "",
				layer.blockedCode === void 0 ? "" : `— ${reasonText(state, layer.blockedCode)}`,
				layer.path ?? ""
			].filter((part) => part.length > 0).join("  ")
		})) }) : null);
	}
	/**
	* 密钥面板。
	*
	* 与其他层的关键差别：**宿主永远不回传值**，所以草稿从**空**开始，
	* 界面只能表达"已配置 / 未配置 / 被遮蔽"。这不是 UI 的保守选择，
	* 而是 `dsh-credentials` 的契约（`describe()` 的返回类型没有可以搭载值的
	* 位置）。任何"显示已存密钥"的界面都必然违反该契约。
	*/
	function CredentialPanel(props) {
		const { names, onSaved } = props;
		const [status, setStatus] = useState(null);
		const [available, setAvailable] = useState(true);
		const [error, setError] = useState(null);
		const [editing, setEditing] = useState(null);
		const [draft, setDraft] = useState("");
		const [busy, setBusy] = useState(false);
		const [feedback, setFeedback] = useState(null);
		const key = names.join(",");
		const load = useCallback(() => {
			if (names.length === 0) {
				setStatus({});
				return;
			}
			setError(null);
			fetch("/api/env-manager/credential-state?refs=" + encodeURIComponent(key)).then((res) => res.json()).then((body) => {
				setAvailable(body.available === true);
				setStatus(body.refs || {});
			}).catch((err) => setError(messageOf(err)));
		}, [key, names.length]);
		useEffect(() => {
			load();
		}, [load]);
		const save = useCallback(async () => {
			if (editing === null) return;
			setBusy(true);
			setFeedback(null);
			try {
				await postJson(CREDENTIAL_WRITE_URL, {
					ref: editing,
					value: draft
				});
				setEditing(null);
				setDraft("");
				setFeedback("已保存");
				load();
				if (onSaved) onSaved();
			} catch (err) {
				setFeedback("保存失败：" + messageOf(err));
			} finally {
				setBusy(false);
			}
		}, [
			editing,
			draft,
			load,
			onSaved
		]);
		const remove = useCallback(async () => {
			if (editing === null) return;
			setBusy(true);
			setFeedback(null);
			try {
				await postJson(CREDENTIAL_WRITE_URL, {
					ref: editing,
					unset: true
				});
				setEditing(null);
				setDraft("");
				setFeedback("已删除");
				load();
				if (onSaved) onSaved();
			} catch (err) {
				setFeedback("删除失败：" + messageOf(err));
			} finally {
				setBusy(false);
			}
		}, [
			editing,
			load,
			onSaved
		]);
		if (names.length === 0) return React.createElement(Empty, null, "环境中没有 KEY / TOKEN / SECRET 形状的变量名");
		return React.createElement(React.Fragment, null, React.createElement(GroupHeading, {
			title: "密钥（凭据域）",
			count: names.length
		}), React.createElement(Note, null, "宿主的凭据域**只提供\"是否已配置\"**，任何开关都拿不到密钥值 —— 写入后立即对 DSH 内部生效（下一次模型请求即可用），但模型执行的 shell 也读不到它，这是有意的安全设计。"), available === false ? React.createElement(Note, null, "本 composition 未挂载凭据域，无法管理密钥。") : null, error !== null ? React.createElement(Note, null, `读取失败：${error}`) : null, feedback !== null ? React.createElement(Note, null, feedback) : null, status === null ? React.createElement(Empty, null, "正在读取密钥状态…") : names.map((name) => {
			const info = status[name] ?? {
				configured: false,
				editable: false
			};
			const rowMeta = React.createElement(Meta, { parts: [
				info.configured === true ? "已配置" : "未配置",
				info.sourceLabel,
				info.blockedReason
			] });
			return React.createElement("div", { key: name }, React.createElement(Row, { active: editing === name }, React.createElement(Key, { title: name }, name), React.createElement(Value, {
				masked: info.configured === true,
				title: info.configured === true ? "宿主从不回传密钥值" : void 0,
				children: info.configured === true ? null : "—"
			}), React.createElement("span", { style: {
				display: "inline-flex",
				alignItems: "baseline",
				gap: "8px"
			} }, rowMeta, React.createElement(RowActions, null, info.editable === true && editing !== name ? React.createElement(Button, {
				variant: "ghost",
				size: "sm",
				icon: React.createElement(IconEditOutline16, null),
				title: info.configured === true ? "替换密钥" : "设置密钥",
				"aria-label": info.configured === true ? "替换" : "设置",
				disabled: busy,
				onClick: () => {
					setEditing(name);
					setDraft("");
					setFeedback(null);
				}
			}) : null))), editing === name ? React.createElement("div", { style: {
				display: "flex",
				alignItems: "center",
				gap: "6px",
				padding: "2px 8px 6px"
			} }, React.createElement(Input, {
				style: {
					flex: 1,
					fontFamily: MONO,
					fontSize: "12px"
				},
				type: "password",
				placeholder: "输入新值（不会回显已存值）",
				value: draft,
				autoFocus: true,
				onChange: (e) => setDraft(e.target.value)
			}), React.createElement(Button, {
				variant: "outline",
				size: "sm",
				disabled: busy,
				onClick: save
			}, busy ? "保存中" : "保存"), React.createElement(Button, {
				variant: "ghost",
				size: "sm",
				disabled: busy,
				onClick: () => {
					setEditing(null);
					setDraft("");
				}
			}, "取消"), info.configured === true ? React.createElement(Button, {
				variant: "ghost",
				size: "sm",
				icon: React.createElement(IconTrashOutline16, null),
				title: "删除密钥",
				"aria-label": "删除",
				disabled: busy,
				onClick: remove
			}) : null) : null);
		}));
	}
	/** 变量面板主体（模态框里的内容）。 */
	function EnvManagerPanel() {
		const [state, setState] = useState(null);
		const [error, setError] = useState(null);
		const [loading, setLoading] = useState(true);
		const [expanded, setExpanded] = useState({});
		const [filter, setFilter] = useState("");
		const [notesOpen, setNotesOpen] = useState(false);
		/**
		* 是否让宿主回传敏感名的值。**默认 false**，且不持久化 —— 每次打开都要重新
		* 打开它。打开时请求带 `reveal=all`，宿主才会对名字像密钥的变量回摘要
		* （见设计文档 §33：这是"用户明确要看"与"默认不落到浏览器"之间的取舍）。
		*/
		const [revealSecrets, setRevealSecrets] = useState(false);
		const load = useCallback(() => {
			setLoading(true);
			setError(null);
			fetch(revealSecrets ? STATE_URL + "?reveal=all" : STATE_URL).then((res) => {
				if (!res.ok) throw new Error("HTTP " + String(res.status));
				return res.json();
			}).then((body) => {
				setState(body);
				setLoading(false);
			}).catch((err) => {
				setError(messageOf(err));
				setLoading(false);
			});
		}, [revealSecrets]);
		useEffect(() => {
			load();
		}, [load]);
		const toggle = useCallback((name) => {
			setExpanded((prev) => ({
				...prev,
				[name]: !prev[name]
			}));
		}, []);
		if (loading && state === null) return React.createElement(Placeholder, null, "正在读取环境…");
		if (error !== null) return React.createElement(React.Fragment, null, React.createElement(Placeholder, { tone: "warn" }, `读取失败：${error}`), React.createElement(Note, null, `宿主路由：${STATE_URL}（需要 DSH 已加载本插件）`), React.createElement("div", { style: {
			display: "flex",
			justifyContent: "center"
		} }, React.createElement(Button, {
			variant: "outline",
			size: "sm",
			onClick: load
		}, "重试")));
		if (state === null) return null;
		const variables = state.variables ?? [];
		const needle = filter.trim().toUpperCase();
		const shown = needle.length === 0 ? variables : variables.filter((v) => v.name.toUpperCase().includes(needle));
		/**
		* 分组顺序 = **"我能不能改、我多常看"**，不是环境模型里的信任顺序。
		*
		* 环境模型把「启动环境」放在最高优先级（它确实最权威），但界面照那个顺序排
		* 的话，首屏全是 `ComSpec` / `DriverData` / `FRP_HOME` 这类系统继承来的噪音，
		* 而用户真正要改的东西（项目 `.env`、`$DSH_HOME/.env`、凭据）被压到看不见的
		* 地方。
		*
		* 所以分组依据是**"要改它该去哪一层"**（第一个可写的层），而不是"当前谁在生效"：
		* `PATH` 的值现在来自启动环境，但你能在项目 `.env` 里覆盖它 —— 它属于项目组，
		* 而不是"只读继承"。当前生效层仍然写在每行的注解里（`启动环境`），信息没丢。
		*
		* 这样得到一条很好读的规则：**上面几组都能改，最后一组不能改**。
		* 多层竞争不再单独成组 —— 它已经是行尾的 `遮蔽 N 层`，展开各层即可看到。
		*/
		const WRITABLE_ORDER = [
			"project-env",
			"user-env",
			"os-user",
			"os-machine"
		];
		/** 要改这个变量该去哪一层：第一个可写的层；没有则 undefined。 */
		const writableLayerOf = (v) => WRITABLE_ORDER.find((layer) => v.layers.some((l) => l.layer === layer && l.writable === true));
		const LAYER_ORDER = [
			{
				key: "runtime",
				title: "运行时 DSH_*",
				effective: ""
			},
			{
				key: "project-env",
				title: "项目 .env",
				effective: "project-env"
			},
			{
				key: "user-env",
				title: "用户 .env（$DSH_HOME）",
				effective: "user-env"
			},
			{
				key: "credential",
				title: "凭据库",
				effective: "credential"
			},
			{
				key: "os-user",
				title: "注册表 · 用户",
				effective: "os-user"
			},
			{
				key: "os-machine",
				title: "注册表 · 系统",
				effective: "os-machine"
			},
			{
				key: "readonly",
				title: "启动环境（无处可写，只读）",
				effective: "process"
			}
		];
		const byName = (a, b) => a.name.localeCompare(b.name, "en", {
			sensitivity: "base",
			numeric: true
		});
		const belongs = (v, entry) => {
			if (entry.key === "runtime") return v.runtimeManaged === true;
			if (v.runtimeManaged === true) return false;
			if (entry.key === "credential") return v.effective === "credential";
			if (entry.key === "readonly") return true;
			return writableLayerOf(v) === entry.effective || v.effective === entry.effective;
		};
		const claimed = /* @__PURE__ */ new Set();
		const groups = LAYER_ORDER.map((entry) => {
			const items = shown.filter((v) => !claimed.has(v.name) && belongs(v, entry));
			for (const item of items) claimed.add(item.name);
			return {
				key: entry.key,
				title: entry.title,
				items: [...items].sort(byName)
			};
		});
		const unclaimed = shown.filter((v) => !claimed.has(v.name)).sort(byName);
		if (unclaimed.length > 0) groups.push({
			key: "other",
			title: "其它层",
			items: unclaimed
		});
		const credentialNames = variables.filter((v) => CREDENTIAL_HINTS.test(v.name)).map((v) => v.name).sort();
		const warnings = state.warnings ?? [];
		const sensitiveCount = variables.filter((v) => v.sensitive === true).length;
		return React.createElement(React.Fragment, null, React.createElement(Toolbar, null, React.createElement(Input, {
			icon: React.createElement(IconSearchOutline16, null),
			placeholder: "按名称过滤",
			value: filter,
			style: {
				flex: 1,
				fontSize: "12px"
			},
			onChange: (e) => setFilter(e.target.value)
		}), React.createElement(Button, {
			variant: "ghost",
			size: "sm",
			icon: React.createElement(IconRefreshOutline16, null),
			title: "重新读取",
			"aria-label": "刷新",
			onClick: load
		}), React.createElement("span", { style: {
			...T.meta,
			fontVariantNumeric: "tabular-nums",
			whiteSpace: "nowrap"
		} }, needle.length === 0 ? String(variables.length) : `${String(shown.length)} / ${String(variables.length)}`), React.createElement(Switch, {
			checked: revealSecrets,
			onChange: (next) => setRevealSecrets(next),
			label: "显示敏感值",
			disabled: sensitiveCount === 0,
			title: (revealSecrets ? "已打开：名字像密钥的变量会带上真实值一起传到浏览器。" : `默认关闭：宿主只回长度不回值（当前有 ${String(sensitiveCount)} 个名字像密钥）。打开后会重新请求一次。`) + "凭据库始终不含值。"
		})), warnings.map((w, i) => React.createElement(Note, { key: `w${String(i)}` }, `⚠ ${w.path === void 0 ? "" : `${w.path}：`}${w.message ?? w.code ?? ""}`)), React.createElement(ScrollArea, null, (() => {
			const afterKey = groups.some((g) => g.key === "credential" && g.items.length > 0) ? "credential" : "user-env";
			const nodes = [];
			for (const group of groups) {
				if (group.items.length === 0) continue;
				nodes.push(React.createElement(GroupHeading, {
					key: `h-${group.key}`,
					title: group.title,
					count: group.items.length
				}), ...group.items.slice(0, 40).map((v) => React.createElement(VariableRow, {
					key: v.name,
					variable: v,
					state,
					expanded: expanded[v.name] === true,
					revealSecrets,
					onToggle: toggle,
					onSaved: load
				})), group.items.length > 40 ? React.createElement(Note, { key: `m-${group.key}` }, `另有 ${String(group.items.length - 40)} 项，请用过滤框缩小范围`) : null);
				if (group.key === afterKey) nodes.push(React.createElement(CredentialPanel, {
					key: "credentials",
					names: credentialNames,
					onSaved: load
				}));
			}
			return nodes;
		})(), shown.length === 0 ? React.createElement(Empty, null, `没有名字匹配「${filter}」`) : null), React.createElement(DisclosureRow, {
			title: "说明与生效时机",
			open: notesOpen,
			expandable: true,
			onToggle: () => setNotesOpen(!notesOpen)
		}, React.createElement("div", { style: { paddingBottom: "4px" } }, React.createElement(Note, null, `工作目录 ${state.cwd}　·　home ${state.home}　·　共 ${String(state.counts.total)} 项` + (state.counts.shadowed > 0 ? `（${String(state.counts.shadowed)} 项多层竞争）` : "")), React.createElement(Note, null, `项目 .env：${state.files.project ?? "（不存在）"}　·　用户 .env：${state.files.user ?? "（不存在）"}`), state.os === void 0 ? null : React.createElement(Note, null, state.os.skipped === true ? "OS 环境层：本次请求已跳过（os=0）" : state.os.supported === false ? "OS 环境层：当前平台不支持读写（Linux/macOS 没有单一可靠的写入点，见设计文档 §2）" : `OS 环境层：注册表·用户 ${String(state.os.scopes?.["os-user"]?.count ?? 0)} 项` + (state.os.scopes?.["os-user"]?.error ? `（读取失败：${state.os.scopes["os-user"]?.error ?? ""}）` : "") + `　·　注册表·系统 ${String(state.os.scopes?.["os-machine"]?.count ?? 0)} 项` + (state.os.scopes?.["os-machine"]?.error ? `（读取失败：${state.os.scopes["os-machine"]?.error ?? ""}）` : "")), React.createElement(Note, null, "标记为「shell 不可见」的名字会被子进程清洗（/KEY|PASSWORD|SECRET|TOKEN/i），所以模型执行的命令读不到它们 —— 这是「仅 DSH 内部可用」的密钥。"), React.createElement(Note, null, "注册表层的改动在 DSH 重启前**不会改变生效值** —— 注册表的值在启动时已被继承进「启动环境」，而它的优先级更高。展开被遮蔽的多层变量即可看到这种竞争。"), React.createElement(Note, null, "写入 .env 使用「读取 revision → 带栅栏写入」的乐观并发；若期间文件被其他程序改动，保存会被拒绝而不会覆盖对方的改动。"))));
	}
	/**
	* 本插件依赖的 cordis 服务（**浏览器侧的 fiber inject**）。
	*
	* 这是 `cannot get property "slots" without inject` 检查的那个 inject。
	*
	* 两次修错的过程记在这里，免得重犯：
	*
	*   1. 改 `package.json` 的 `dsh.client.inject`（列包名）→ **无效**。
	*      那是 `dsh-client-modules` 的组合机制，只管 boot graph 的加载顺序，
	*      不解除 cordis 的服务访问限制。
	*   2. 我以为客户端 bundle 必须"return 插件对象"→ 也没解决。
	*
	* 真正的依据在 cordis 与第一方产物里：
	*   - cordis registry：`new Fiber(this.ctx, config, Inject.resolve(plugin.inject), …)`
	*     —— 它读的是**传进 ctx.plugin() 的那个对象**的 `inject`
	*   - 客户端 runner 传的是 materialize 出的 `module.exports`
	*   - 第一方产物结尾就是 `exports.apply = apply; exports.inject = inject;`
	*     （如 `dsh-client-ui-goal`）
	*
	* 所以：**具名导出 `inject`（服务名数组）+ 具名导出 `apply`**，与第一方一致。
	* 服务名只有 `"slots"`；槽位就绪由 `slots.inject()` 自己处理。
	*/
	const inject = ["slots"];
	/**
	* 入口图标。
	*
	* `IconContextInjectionOutline16` —— 本插件做的事就是往 DSH 的上下文里注入变量，
	* 语义对得上，尺寸与 header 里其它图标一致。想换只改这一行，候选：
	* `IconDataOutline16`（层叠的数据）、`IconDatabaseOutline16`（分层存储）、
	* `IconSettingsOutline16`。
	*/
	const ENTRY_ICON = IconContextInjectionOutline16;
	/**
	* 模态框：把面板挂在 body 上的 portal，由 `Modal` 自己处理遮罩、Esc、焦点。
	*
	* 只在打开时才渲染 —— `Modal` 在 `open === false` 时返回 null，所以关闭状态下
	* 一次 `fetch` 都不会发。
	*/
	function EnvManagerDialog(props) {
		return React.createElement(Modal, {
			open: props.open,
			onClose: props.onClose,
			title: "环境变量",
			closeLabel: "关闭",
			description: "KEY=VALUE 的复合视图：谁在生效、在哪一层、能不能改。",
			className: "dsh-envmgr-dialog"
		}, React.createElement(EnvManagerPanel));
	}
	/**
	* 会话头部（`conversation.session.header.utilities`）里的入口。
	*
	* 为什么放在这里而不是 Settings → Plugins：环境变量是**每次会话都要看**的东西
	* （"这个变量到底生效了吗"），而 Settings 是配置一次就不再打开的页面。
	* 头部图标点开即成模态，不离开当前对话。
	*/
	function EnvManagerAction() {
		const [open, setOpen] = useState(false);
		return React.createElement(React.Fragment, null, React.createElement(Button, {
			variant: "ghost",
			size: "sm",
			icon: React.createElement(ENTRY_ICON, null),
			title: "环境变量",
			"aria-label": "环境变量",
			onClick: () => setOpen(true)
		}), React.createElement(EnvManagerDialog, {
			open,
			onClose: () => setOpen(false)
		}));
	}
	/**
	* 载入客户端插件。
	*
	* `ctx` 只声明**用到的**那一小块（`slots.inject` / `slots.register`）：
	* 客户端 runner 传进来的是它自己的 cordis 上下文，本包不该、也无法完整声明它。
	* 真正要保证的是 `inject = ['slots']` 已导出 —— 没有它，cordis 会以
	* `cannot get property "slots" without inject` 直接拒绝装载。
	*
	* @param ctx - 客户端 cordis 上下文（已因 `inject` 而保证 `ctx.slots` 可用）。
	*/
	function apply(ctx) {
		installClientStyles();
		ctx.slots.inject("conversation.session.header.utilities", () => ctx.slots.register({
			name: "conversation.session.header.utilities",
			id: "env-manager",
			order: 100
		}, EnvManagerAction));
	}
	//#endregion

	exports.EnvManagerAction = EnvManagerAction;
	exports.EnvManagerPanel = EnvManagerPanel;
	exports.apply = apply;
	exports.inject = inject;
	return module.exports
	}
})
