/* Generated by build/client-wrapper.mjs — do not edit by hand. */
window.__ModuleLoader__.load({
	id: "dsh-environment-tray",
	factory: (require) => {
		const module = { exports: {} }
		const exports = module.exports
		Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' })
const React = require("react")
const Primitives = require("@deepseek-ai/dsh-client-ui-primitives")
const { Button, Input, Modal } = require("@deepseek-ai/dsh-client-ui-primitives")
	//#region src/inline-edit.ts
	/** One edit session; blur and Enter share a synchronous submission lock. */
	function useInlineEdit(options) {
		const [editing, setEditing] = React.useState(false);
		const [draft, setDraft] = React.useState("");
		const [ready, setReady] = React.useState(false);
		const [busy, setBusy] = React.useState(false);
		const [error, setError] = React.useState(null);
		const [visible, setVisible] = React.useState(false);
		const session = React.useRef({
			generation: 0,
			active: false,
			pending: false,
			suspended: false,
			original: "",
			revision: void 0
		});
		React.useEffect(() => () => {
			session.current.active = false;
			session.current.suspended = false;
			session.current.generation += 1;
			session.current.original = "";
			session.current.revision = void 0;
		}, []);
		const cancel = () => {
			session.current.active = false;
			session.current.suspended = false;
			session.current.generation += 1;
			session.current.original = "";
			session.current.revision = void 0;
			setEditing(false);
			setDraft("");
			setVisible(false);
			setError(null);
			setBusy(false);
		};
		const begin = async () => {
			if (!options.read || session.current.pending) return;
			const generation = ++session.current.generation;
			session.current.active = true;
			session.current.suspended = false;
			setEditing(true);
			setDraft("");
			setReady(false);
			setBusy(true);
			setVisible(false);
			setError(null);
			try {
				const value = await options.read();
				if (generation !== session.current.generation) return;
				session.current.original = value.value;
				session.current.revision = value.revision;
				setDraft(value.value);
				setReady(true);
			} catch (error) {
				if (generation === session.current.generation) setError(error);
			} finally {
				if (generation === session.current.generation) setBusy(false);
			}
		};
		const submit = async (remove = false) => {
			if (!session.current.active || session.current.pending || session.current.suspended || !ready) return;
			if (!remove && draft === session.current.original) {
				cancel();
				return;
			}
			if (remove && !options.remove) return;
			session.current.pending = true;
			const generation = session.current.generation;
			setBusy(true);
			setError(null);
			try {
				const result = remove ? await options.remove(session.current.revision) : await options.write(draft, session.current.revision);
				if (generation !== session.current.generation) return;
				cancel();
				options.onSaved(result);
			} catch (error) {
				if (generation === session.current.generation) setError(error);
			} finally {
				session.current.pending = false;
				if (generation === session.current.generation) setBusy(false);
			}
		};
		const onBlur = (event) => {
			if (event.relatedTarget?.getAttribute?.("data-dsh-environment-tray-copy") === "true") return;
			if (!event.currentTarget.contains(event.relatedTarget)) submit();
		};
		const onKeyDown = (event) => {
			if (event.nativeEvent?.isComposing) return;
			if (event.key === "Escape") {
				event.preventDefault();
				event.stopPropagation();
				if (!session.current.pending) cancel();
			} else if (event.key === "Enter") {
				event.preventDefault();
				submit();
			}
		};
		return {
			editing,
			draft,
			setDraft,
			ready,
			busy,
			error,
			visible,
			setVisible,
			begin,
			cancel,
			pause: () => {
				session.current.suspended = true;
			},
			resume: () => {
				session.current.suspended = false;
			},
			remove: () => submit(true),
			onBlur,
			onKeyDown
		};
	}
	//#endregion
	//#region src/client-locales.ts
	/** Dictionaries owned by this plugin; language selection belongs to DSH. */
	const LOCALE_NS = "dsh-environment-tray";
	const dictionaries = {
		zh: {
			title: "环境变量",
			close: "关闭",
			search: "搜索变量",
			refresh: "刷新",
			retry: "重试",
			newVariable: "新建变量",
			variableName: "名称",
			variableValue: "值",
			saveTo: "保存位置",
			create: "新建",
			cancel: "取消",
			deleteVariable: "删除变量",
			deleteFrom: "从{layer}删除",
			deletePrompt: "从{layer}删除 {name}？",
			deleteFallback: "其他层中的同名值会保留。",
			confirmDelete: "确认删除",
			loading: "读取中…",
			loadingEnvironment: "正在读取环境…",
			saving: "保存中…",
			readError: "读取失败：{error}",
			restart: "需重启 DSH",
			deleted: "已删除 {name}",
			undoDelete: "撤销删除",
			noMatches: "没有匹配的变量",
			valueLabel: "{name} 的值",
			editHint: "Enter 保存 · Esc 取消",
			multilineHint: "显示后编辑多行值",
			hideInput: "隐藏输入",
			showInput: "显示输入",
			hideValue: "隐藏值",
			showValue: "显示值",
			copyValue: "复制值",
			copied: "已复制",
			cancelEdit: "取消编辑",
			edit: "编辑",
			delete: "删除",
			replace: "替换",
			set: "设置",
			collapseLayers: "收起各层",
			expandLayers: "展开各层",
			current: "当前",
			layerCount: "{count} 层",
			unset: "未设置",
			"layer.process": "当前进程",
			"layer.project": "项目 .env",
			"layer.user": "用户 .env",
			"layer.credential": "凭据",
			"layer.osUser": "Windows 用户环境变量",
			"layer.osMachine": "Windows 系统环境变量",
			"layer.file": "凭据库",
			"group.runtime": "DSH 运行变量",
			"group.credential": "凭据环境",
			"group.readonly": "当前进程 · 只读",
			scopeReadError: "{scope}读取失败",
			"warning.bom": "{path}：请去掉 UTF-8 BOM，以便 DSH 正确读取第一个变量。",
			"blocked.process": "当前进程层只读",
			"blocked.proxy": "请在用户 .env 设置代理",
			"blocked.bootstrap": "请在启动 DSH 前设置",
			"blocked.unknown": "不支持此环境层",
			"blocked.elevation": "需要管理员权限",
			"error.read": "读取失败",
			"error.copy": "复制失败",
			"error.edit": "无法编辑",
			"error.reopen": "请重新打开编辑",
			"error.stale": "文件已被其他程序修改，请重新打开编辑后再保存。",
			"error.emptyName": "变量名不能为空",
			"error.invalidName": "变量名只能由字母、数字、下划线组成，且不能以数字开头",
			"error.nameSpace": "变量名不能包含空白字符",
			"error.lossy": "此值无法原样保存在 .env 中",
			"error.validation": "编辑内容无效",
			"error.noEdits": "没有需要保存的改动",
			"error.credentials": "凭据服务不可用",
			"error.invalidRef": "凭据名称无效",
			"error.emptyValue": "密钥不能为空，请使用删除操作移除",
			"error.shadowed": "此凭据被更高优先级的来源覆盖",
			"error.invalidLayer": "环境层无效",
			"error.invalidRequest": "请求无效",
			"error.platform": "当前平台不支持编辑系统环境变量",
			"error.missing": "值已不存在，请刷新列表",
			"error.policy": "请重新连接 DSH 以验证请求",
			"error.origin": "请求来源不受信任",
			"error.auth": "请重新连接 DSH 完成认证",
			"error.exists": "所选位置中已存在同名变量",
			"error.registryRead": "无法读取所选位置，未执行新建"
		},
		en: {
			title: "Environment variables",
			close: "Close",
			search: "Search variables",
			refresh: "Refresh",
			retry: "Retry",
			newVariable: "New variable",
			variableName: "Name",
			variableValue: "Value",
			saveTo: "Save to",
			create: "Create",
			cancel: "Cancel",
			deleteVariable: "Delete variable",
			deleteFrom: "Delete from {layer}",
			deletePrompt: "Delete {name} from {layer}?",
			deleteFallback: "Values in other layers will remain.",
			confirmDelete: "Confirm deletion",
			loading: "Loading…",
			loadingEnvironment: "Loading environment…",
			saving: "Saving…",
			readError: "Could not read: {error}",
			restart: "Restart DSH to apply",
			deleted: "Deleted {name}",
			undoDelete: "Undo deletion",
			noMatches: "No matching variables",
			valueLabel: "Value of {name}",
			editHint: "Enter to save · Esc to cancel",
			multilineHint: "Reveal to edit multiple lines",
			hideInput: "Hide input",
			showInput: "Show input",
			hideValue: "Hide value",
			showValue: "Show value",
			copyValue: "Copy value",
			copied: "Copied",
			cancelEdit: "Cancel editing",
			edit: "Edit",
			delete: "Delete",
			replace: "Replace",
			set: "Set",
			collapseLayers: "Collapse layers",
			expandLayers: "Expand layers",
			current: "Current",
			layerCount: "{count} layers",
			unset: "Not set",
			"layer.process": "Current process",
			"layer.project": "Project .env",
			"layer.user": "User .env",
			"layer.credential": "Credentials",
			"layer.osUser": "Windows user variables",
			"layer.osMachine": "Windows system variables",
			"layer.file": "Credential store",
			"group.runtime": "DSH runtime variables",
			"group.credential": "Credential environment",
			"group.readonly": "Current process · Read only",
			scopeReadError: "Could not read {scope}",
			"warning.bom": "{path}: Remove the UTF-8 BOM so DSH can read the first variable correctly.",
			"blocked.process": "Current process layer is read only",
			"blocked.proxy": "Set the proxy in User .env",
			"blocked.bootstrap": "Set before starting DSH",
			"blocked.unknown": "Unsupported environment layer",
			"blocked.elevation": "Administrator access required",
			"error.read": "Could not read the value",
			"error.copy": "Could not copy the value",
			"error.edit": "Cannot edit this value",
			"error.reopen": "Reopen the editor to read the latest value",
			"error.stale": "The file changed. Reopen the editor before saving.",
			"error.emptyName": "Variable name cannot be empty",
			"error.invalidName": "Use letters, digits and underscores; start with a letter or underscore",
			"error.nameSpace": "Variable name cannot contain whitespace",
			"error.lossy": "This value cannot be stored in .env without changing it",
			"error.validation": "Invalid changes",
			"error.noEdits": "No changes to save",
			"error.credentials": "Credential service unavailable",
			"error.invalidRef": "Invalid credential name",
			"error.emptyValue": "Credential cannot be empty; use Delete to remove it",
			"error.shadowed": "A higher priority source overrides this credential",
			"error.invalidLayer": "Invalid environment layer",
			"error.invalidRequest": "Invalid request",
			"error.platform": "Editing system variables is not supported on this platform",
			"error.missing": "This value no longer exists; refresh the list",
			"error.policy": "Reconnect to DSH to verify this request",
			"error.origin": "Request origin is not trusted",
			"error.auth": "Reconnect to DSH to authenticate",
			"error.exists": "This name already exists in the selected location",
			"error.registryRead": "Could not read the selected location; nothing was created"
		}
	};
	const layerKeys = {
		process: "layer.process",
		"project-env": "layer.project",
		"user-env": "layer.user",
		credential: "layer.credential",
		"os-user": "layer.osUser",
		"os-machine": "layer.osMachine",
		env: "layer.process",
		file: "layer.file"
	};
	const layerLabel = (t, layer) => layerKeys[layer] ? t(layerKeys[layer]) : layer;
	const codeKeys = {
		"read-failed": "error.read",
		"copy-failed": "error.copy",
		"not-editable": "error.edit",
		"reopen-editor": "error.reopen",
		"stale-revision": "error.stale",
		"empty-name": "error.emptyName",
		"invalid-name": "error.invalidName",
		"name-has-space": "error.nameSpace",
		"lossy-value": "error.lossy",
		"validation-failed": "error.validation",
		"no-edits": "error.noEdits",
		"invalid-ref": "error.invalidRef",
		"credentials-unavailable": "error.credentials",
		"empty-value": "error.emptyValue",
		"credential-shadowed": "error.shadowed",
		"invalid-layer": "error.invalidLayer",
		"unsupported-platform": "error.platform",
		"value-missing": "error.missing",
		"request-policy-unavailable": "error.policy",
		"untrusted-origin": "error.origin",
		"unauthenticated": "error.auth",
		"invalid-edits": "error.invalidRequest",
		"invalid-revision": "error.invalidRequest",
		"invalid-value": "error.invalidRequest",
		"invalid-type": "error.invalidRequest",
		"invalid-scope": "error.invalidRequest",
		"process-inherited": "blocked.process",
		"process-layer": "blocked.process",
		"proxy-not-in-home": "blocked.proxy",
		"bootstrap-only": "blocked.bootstrap",
		"unknown-layer": "blocked.unknown",
		"needs-elevation": "blocked.elevation",
		"already-exists": "error.exists",
		"registry-read-failed": "error.registryRead"
	};
	const reasonLabel = (t, code, fallback) => codeKeys[code] ? t(codeKeys[code]) : fallback ?? code;
	/** Keep codes in state so mounted errors also follow a locale change. */
	var ClientError = class extends Error {
		response;
		status;
		constructor(response, status) {
			super(response.message ?? response.error ?? `HTTP ${status}`);
			this.response = response;
			this.status = status;
		}
	};
	function errorLabel(t, error) {
		if (error instanceof ClientError) {
			const { response } = error;
			if (response.problems?.length) return response.problems.map((problem) => {
				const text = problem.code ? reasonLabel(t, problem.code, problem.message) : problem.message;
				return (problem.name ? `${problem.name}: ` : "") + (text ?? t("error.validation"));
			}).join("; ");
			return response.error ? reasonLabel(t, response.error, response.message) : response.message ?? `HTTP ${error.status}`;
		}
		return error instanceof Error ? error.message : String(error);
	}
	//#endregion
	//#region src/client-actions.ts
	function EyeIcon(props) {
		return React.createElement("svg", {
			width: 16,
			height: 16,
			viewBox: "0 0 24 24",
			fill: "none",
			stroke: "currentColor",
			strokeWidth: 1.6,
			"aria-hidden": true
		}, React.createElement("path", { d: "M2 12s3.5-7 10-7 10 7-3.5 7-10 7S2 12 2 12Z" }), React.createElement("circle", {
			cx: 12,
			cy: 12,
			r: 3
		}), props.hidden ? React.createElement("path", { d: "m3 3 18 18" }) : null);
	}
	function PlusIcon() {
		return React.createElement("svg", {
			width: 16,
			height: 16,
			viewBox: "0 0 24 24",
			fill: "none",
			stroke: "currentColor",
			strokeWidth: 1.6,
			"aria-hidden": true
		}, React.createElement("path", { d: "M12 5v14M5 12h14" }));
	}
	function NewVariableButton({ t, onClick }) {
		return React.createElement(Button, {
			variant: "ghost",
			size: "sm",
			icon: React.createElement(PlusIcon),
			onClick,
			title: t("newVariable"),
			"aria-label": t("newVariable")
		});
	}
	/** Explicit submission: moving between the three new-variable fields never saves. */
	function NewVariableForm(props) {
		const { t } = props;
		const [layer, setLayer] = React.useState("user-env");
		const [name, setName] = React.useState("");
		const [value, setValue] = React.useState("");
		const [visible, setVisible] = React.useState(false);
		const [busy, setBusy] = React.useState(false);
		const [error, setError] = React.useState(null);
		const session = React.useRef({
			active: true,
			pending: false
		});
		React.useEffect(() => {
			session.current.active = true;
			return () => {
				session.current.active = false;
			};
		}, []);
		const cancel = () => {
			if (session.current.pending) return;
			session.current.active = false;
			setName("");
			setValue("");
			setVisible(false);
			props.onCancel();
		};
		const submit = async (event) => {
			event.preventDefault();
			if (!session.current.active || session.current.pending) return;
			const key = name.trim();
			setError(null);
			if (!key || !/^[A-Za-z_][A-Za-z0-9_]*$/.test(key)) {
				setError(new ClientError({ error: key ? "invalid-name" : "empty-name" }));
				return;
			}
			session.current.pending = true;
			setBusy(true);
			try {
				await props.create(layer, key, value);
			} catch (error) {
				if (session.current.active) setError(error);
			} finally {
				session.current.pending = false;
				if (session.current.active) setBusy(false);
			}
		};
		const sensitive = /KEY|PASSWORD|SECRET|TOKEN/i.test(name);
		const masked = sensitive && !visible;
		const multiline = /[\r\n]/.test(value);
		return React.createElement("form", {
			className: "dsh-environment-tray-create",
			"aria-label": t("newVariable"),
			onSubmit: submit,
			onKeyDown: (event) => {
				if (event.key === "Escape" && !event.nativeEvent?.isComposing) {
					event.preventDefault();
					event.stopPropagation();
					cancel();
				}
			}
		}, React.createElement("div", { className: "dsh-environment-tray-create-fields" }, React.createElement("label", null, t("saveTo"), React.createElement("select", {
			className: "dsh-environment-tray-input",
			"aria-label": t("saveTo"),
			value: layer,
			disabled: busy,
			onChange: (event) => {
				setLayer(event.target.value);
				setError(null);
			}
		}, props.layers.map((layer) => React.createElement("option", {
			key: layer,
			value: layer
		}, layerLabel(t, layer))))), React.createElement("label", null, t("variableName"), React.createElement(Input, {
			"aria-label": t("variableName"),
			value: name,
			autoFocus: true,
			disabled: busy,
			autoComplete: "off",
			spellCheck: false,
			"aria-invalid": error !== null,
			onChange: (event) => {
				setName(event.target.value);
				setVisible(false);
				setError(null);
			}
		})), React.createElement("label", { className: "dsh-environment-tray-create-value" }, t("variableValue"), React.createElement("span", null, React.createElement(masked ? "input" : "textarea", {
			className: "dsh-environment-tray-input",
			"aria-label": t("variableValue"),
			value,
			type: masked ? "password" : void 0,
			rows: 2,
			disabled: busy,
			readOnly: masked && multiline,
			autoComplete: "off",
			spellCheck: false,
			title: masked && multiline ? t("multilineHint") : void 0,
			onChange: (event) => setValue(event.target.value)
		}), sensitive ? React.createElement(Button, {
			type: "button",
			variant: "ghost",
			size: "sm",
			disabled: busy,
			icon: React.createElement(EyeIcon, { hidden: visible }),
			title: t(visible ? "hideInput" : "showInput"),
			"aria-label": t(visible ? "hideInput" : "showInput"),
			onClick: () => setVisible(!visible)
		}) : null))), error !== null ? React.createElement("p", { role: "alert" }, errorLabel(t, error)) : null, React.createElement("div", { className: "dsh-environment-tray-form-actions" }, React.createElement(Button, {
			type: "button",
			variant: "ghost",
			size: "sm",
			disabled: busy,
			onClick: cancel
		}, t("cancel")), React.createElement(Button, {
			type: "submit",
			variant: "primary",
			size: "sm",
			disabled: busy
		}, t(busy ? "saving" : "create"))));
	}
	function DeleteAction(props) {
		const { t } = props;
		const [open, setOpen] = React.useState(false);
		const [busy, setBusy] = React.useState(false);
		const [error, setError] = React.useState(null);
		const session = React.useRef({
			active: true,
			pending: false
		});
		React.useEffect(() => {
			session.current.active = true;
			return () => {
				session.current.active = false;
			};
		}, []);
		const close = () => {
			if (!session.current.pending) {
				setOpen(false);
				setError(null);
				props.onClose();
			}
		};
		const remove = async () => {
			if (session.current.pending || !open || props.disabled) return;
			session.current.pending = true;
			setBusy(true);
			setError(null);
			try {
				await props.remove();
				if (session.current.active) setOpen(false);
			} catch (error) {
				if (session.current.active) setError(error);
			} finally {
				session.current.pending = false;
				if (session.current.active) setBusy(false);
			}
		};
		return React.createElement(React.Fragment, null, React.createElement(Button, {
			type: "button",
			variant: "ghost",
			size: "sm",
			icon: props.icon,
			disabled: props.disabled,
			title: t("deleteFrom", { layer: layerLabel(t, props.layer) }),
			"aria-label": t("delete"),
			onClick: () => {
				props.onOpen();
				setError(null);
				setOpen(true);
			}
		}), React.createElement(Modal, {
			open,
			title: t("deleteVariable"),
			closeLabel: t("close"),
			className: "dsh-environment-tray-confirm",
			onClose: close,
			footer: React.createElement("div", { className: "dsh-environment-tray-form-actions" }, React.createElement(Button, {
				variant: "ghost",
				size: "sm",
				disabled: busy,
				onClick: close
			}, t("cancel")), React.createElement(Button, {
				variant: "primary",
				size: "sm",
				disabled: busy,
				onClick: remove
			}, t(busy ? "saving" : "confirmDelete")))
		}, React.createElement("p", null, t("deletePrompt", {
			name: props.name,
			layer: layerLabel(t, props.layer)
		})), props.fallback ? React.createElement("p", null, t("deleteFallback")) : null, error !== null ? React.createElement("p", { role: "alert" }, errorLabel(t, error)) : null));
	}
	//#endregion
	//#region src/client-ui.ts
	/**
	* 客户端页签的**表现层**。
	*
	* 与 `client.ts` 的分工：这里只有排版与样式，不认识 `fetch`、也不持有状态；
	* `client.ts` 负责数据流并把结果交给这里的组件。
	*
	* ── 排版原则（这一层的全部理由）────────────────────────────────────────────
	*
	* 「环境变量」这个界面的**内容就是 KEY 与 VALUE**。其余一切都是注解：
	* 生效层、层数、遮蔽、生效时机、平台限制。所以：
	*
	*   1. **KEY / VALUE 占满宽度。** 一行就是 `KEY  VALUE  · 次要信息`，
	*      等宽字体 + 三列对齐，让上百行能像 `env` 输出那样竖着扫下来。
	*   2. **次要信息一律 11px / 低对比。** 不用彩色胶囊、不用边框卡片 ——
	*      胶囊和边框会把注解抬到和内容一样的视觉重量，这是原版"丑"的主因。
	*      次要信息用 `·` 串成一行跟在后面，读得到但抢不走注意力。
	*   3. **操作按需出现。** 编辑/展开是图标按钮，只在悬停该行或键盘落在行内时
	*      出现。密集列表里常驻按钮会让每一行都变成一条按钮条。
	*   4. **分组用一条细横线 + 小字标题**，不要卡片盒子。盒子会切断竖向扫描。
	*   5. **颜色只用于状态**，不用于装饰。正文颜色全部继承
	*      `--dsw-alias-*`（DSH 自己的语义色），所以明暗主题自动正确。
	*
	* 需要 `:hover` / `:focus-within` 的部分走一张注入的极小样式表 —— 内联
	* style 表达不了伪类，而引入 CSS 工具链只为一个悬停态不值得。
	*
	* @module dsh-environment-tray/client-ui
	*/
	/** 等宽字体栈：KEY / VALUE / 路径都用它。 */
	const MONO = "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace";
	/**
	* 字号与不透明度只在这里定义一次。
	*
	* 三档就够：内容（KEY/VALUE）、注解（meta）、结构（分组标题）。
	* 原版的问题是每一类信息都自带一套字号 + 边框 + 颜色，于是没有主次。
	*/
	const T = {
		/** KEY：内容，最高对比、略加粗。 */
		key: {
			fontSize: "12.5px",
			fontWeight: 560,
			letterSpacing: 0
		},
		/** VALUE：内容，等宽、稍低对比（长值要能一眼看出边界）。 */
		value: {
			fontSize: "12.5px",
			fontWeight: 400,
			opacity: .74
		},
		/** 注解：生效层、层数、字符数、时机。 */
		meta: {
			fontSize: "11px",
			fontWeight: 400,
			opacity: .42
		},
		/** 展开后的每层细节。 */
		detail: {
			fontSize: "11.5px",
			fontWeight: 400,
			opacity: .5
		},
		/** 分组标题。 */
		group: {
			fontSize: "11px",
			fontWeight: 520,
			letterSpacing: "0.06em",
			opacity: .5
		}
	};
	/** 注入一次的小样式表：只放内联 style 表达不了的伪类与媒体查询。 */
	const STYLE_ID = "dsh-environment-tray-client-style";
	/**
	* 这张表负责三件内联样式做不到的事：
	*
	* 1. **`:hover` / `:focus-within`** —— 行尾操作按需出现；
	* 2. **响应式** —— 窄屏把三列压成两列，VALUE 换到第二行；
	* 3. **模态框宽度** —— 内容就是 KEY/VALUE，横向越宽越好扫，所以显式放宽到
	*    1080px（`Modal` 自带的默认宽度对这张表偏窄）。能覆盖它是因为两边都是
	*    单类选择器，同优先级下**后出现在文档里的胜出**，而这张表是运行时追加到
	*    `<head>` 末尾的。
	*/
	const CSS = `
	/* Keep the global entry beside the native corner button, even on a blank chat. */
	header[data-window-drag]:has(.dsh-environment-tray-entry) { position: relative; padding-top: 10px; }
	[data-conversation-header-leading]:has(.dsh-environment-tray-entry) { min-height: 30px; }
	header[data-window-drag]:has(.dsh-environment-tray-entry) [data-conversation-header-corner] { padding-inline-start: 38px; }
	.dsh-environment-tray-entry { position: absolute; inset-inline-end: 50px; top: 10px; display: flex; align-items: center; -webkit-app-region: no-drag; }
	.dsh-environment-tray-dialog { width: min(1080px, calc(100vw - 48px)); max-width: none; }
	.dsh-environment-tray-row {
	  display: grid;
	  grid-template-columns: minmax(140px, 260px) minmax(0, 1fr) 220px;
	  align-items: center;
	  column-gap: 12px;
	  padding: 5px 8px;
	  border-radius: 6px;
	}
	.dsh-environment-tray-row:hover { background: var(--dsw-alias-fill-quaternary, rgba(128,128,128,0.10)); }
	.dsh-environment-tray-actions { opacity: 0; transition: opacity .12s ease; }
	.dsh-environment-tray-row-meta { display: grid; grid-template-columns: minmax(0, 1fr) 88px; align-items: center; gap: 8px; min-width: 0; }
	.dsh-environment-tray-row-meta > span:first-child { overflow: hidden; text-overflow: ellipsis; }
	.dsh-environment-tray-actions { display: grid; grid-template-columns: repeat(3, 28px); gap: 2px; min-height: 28px; }
	.dsh-environment-tray-actions button, .dsh-environment-tray-value > button { width: 28px; height: 28px; padding: 0; }
	.dsh-environment-tray-row:hover .dsh-environment-tray-actions,
	.dsh-environment-tray-row:focus-within .dsh-environment-tray-actions { opacity: 1; }
	@media (hover: none) { .dsh-environment-tray-actions { opacity: 1; } }
	.dsh-environment-tray-scroll { max-height: min(62vh, 760px); overflow-y: auto; overscroll-behavior: contain; }
	.dsh-environment-tray-valuecell { min-width: 0; }
	.dsh-environment-tray-value { display: grid; grid-template-columns: minmax(0, 1fr) repeat(2, 28px); align-items: center; gap: 2px; font-family: ${MONO}; }
	.dsh-environment-tray-input { width: 100%; min-width: 0; box-sizing: border-box; padding: 4px 6px; border: 1px solid var(--dsw-alias-border-l2, rgba(128,128,128,.22)); border-radius: 5px; background: transparent; color: inherit; font: inherit; }
	.dsh-environment-tray-input:focus { outline: 1px solid currentColor; outline-offset: -1px; }
	.dsh-environment-tray-input:is(textarea) { resize: vertical; }
	.dsh-environment-tray-input[aria-invalid=true] { border-color: var(--dsw-alias-text-error, #c33); }
	.dsh-environment-tray-value-error { grid-column: 1 / -1; font-family: sans-serif; }
	.dsh-environment-tray-editor { display: flex; align-items: center; gap: 6px; padding: 2px 8px 6px; }
	.dsh-environment-tray-layers { margin: 2px 0 6px; box-shadow: inset 2px 0 var(--dsw-alias-border-l2, rgba(128,128,128,.22)); }
	.dsh-environment-tray-create { margin: 8px 0 12px; padding: 12px; border: 1px solid var(--dsw-alias-border-l2, rgba(128,128,128,.22)); border-radius: 6px; font-size: 12px; }
	.dsh-environment-tray-create-fields { display: grid; grid-template-columns: minmax(0, 1fr) minmax(0, 2fr); gap: 10px; }
	.dsh-environment-tray-create label { display: grid; gap: 5px; min-width: 0; }
	.dsh-environment-tray-create-value { grid-column: 1 / -1; }
	.dsh-environment-tray-create-value > span { display: flex; align-items: start; gap: 6px; }
	.dsh-environment-tray-create select, .dsh-environment-tray-create textarea { font: inherit; }
	.dsh-environment-tray-create option { background: var(--dsw-alias-fill-primary, Canvas); color: var(--dsw-alias-text-primary, CanvasText); }
	.dsh-environment-tray-form-actions { display: flex; justify-content: flex-end; gap: 8px; margin-top: 8px; }
	.dsh-environment-tray-confirm { width: min(440px, calc(100vw - 32px)); }
	.dsh-environment-tray-confirm p { overflow-wrap: anywhere; font-size: 13px; }

	/* 窄屏：KEY 与注解一行，VALUE 独占下一行 —— 竖着扫仍然成立，且不再横向溢出 */
	@media (max-width: 760px) {
	  .dsh-environment-tray-dialog { width: calc(100vw - 16px); }
	  .dsh-environment-tray-row { grid-template-columns: minmax(0, 1fr) 180px; row-gap: 2px; }
	  .dsh-environment-tray-row > .dsh-environment-tray-valuecell { grid-column: 1 / -1; grid-row: 2; }
	  .dsh-environment-tray-row > .dsh-environment-tray-row-meta { grid-column: 2; grid-row: 1; }
	  .dsh-environment-tray-create-fields { grid-template-columns: minmax(0, 1fr); }
	}
	`;
	/**
	* 把上面那张样式表挂进 document（幂等）。
	*
	* 在模块体里调用 —— 客户端 bundle 是惰性 CJS 工厂，工厂体只在首次
	* materialize 时执行，所以挂载前不会有副作用。
	*/
	function installClientStyles() {
		if (typeof document === "undefined") return;
		const existing = document.getElementById(STYLE_ID);
		if (existing !== null) {
			existing.textContent = CSS;
			return;
		}
		const style = document.createElement("style");
		style.id = STYLE_ID;
		style.textContent = CSS;
		document.head.appendChild(style);
	}
	/**
	* 一行。三列网格：KEY 定宽、VALUE 占满、注解靠右。
	*
	* 网格定义在样式表里而不是内联：窄屏要换成两列，而媒体查询赢不过内联样式。
	* KEY 用 `minmax(140px, 260px)`：短名字不浪费空间，遇到
	* `HUOSHAN_DOUBAO_ACCESS_TOKEN` 这种长名字也不会把 VALUE 挤没。
	*/
	function Row(props) {
		return React.createElement("div", {
			className: "dsh-environment-tray-row",
			onBlur: props.onBlur,
			style: { background: props.active === true ? "var(--dsw-alias-fill-quaternary, rgba(128,128,128,0.10))" : "transparent" }
		}, props.children);
	}
	/** 行尾的操作图标簇：默认透明，悬停整行时出现。 */
	function RowActions(props) {
		return React.createElement("span", { className: "dsh-environment-tray-actions" }, props.children ?? [
			React.createElement("span", { key: 0 }),
			React.createElement("span", { key: 1 }),
			React.createElement("span", { key: 2 })
		]);
	}
	/** KEY：内容的主角之一。等宽、高对比、溢出省略。 */
	function Key(props) {
		return React.createElement("span", {
			style: {
				...T.key,
				fontFamily: MONO,
				overflow: "hidden",
				textOverflow: "ellipsis",
				whiteSpace: "nowrap"
			},
			...props.title === void 0 ? {} : { title: props.title }
		}, props.children);
	}
	/**
	* VALUE：另一个主角。等宽、可省略。
	*
	* `masked` 用点阵显示隐藏状态；临时打开的完整值可以换行。
	*/
	function Value(props) {
		return React.createElement("span", {
			className: "dsh-environment-tray-valuecell",
			style: {
				...T.value,
				fontFamily: MONO,
				overflow: "hidden",
				textOverflow: "ellipsis",
				whiteSpace: props.expanded ? "pre-wrap" : "nowrap",
				...props.expanded ? { overflowWrap: "anywhere" } : {},
				...props.onClick === void 0 ? {} : { cursor: "pointer" }
			},
			...props.title === void 0 ? {} : { title: props.title },
			...props.onClick === void 0 ? {} : { onClick: props.onClick }
		}, props.masked === true ? "••••••••••" : props.children);
	}
	/** 注解：一行里跟在 VALUE 后面的全部次要信息，用 `·` 连接。 */
	function Meta(props) {
		const text = props.parts.filter((p) => typeof p === "string" && p.length > 0).join(" · ");
		return React.createElement("span", {
			style: {
				...T.meta,
				whiteSpace: "nowrap"
			},
			title: text
		}, text);
	}
	/** 分组标题：小字 + 一条细横线 + 计数。横向规则把视线按组切开。 */
	function GroupHeading(props) {
		return React.createElement("div", { style: {
			display: "flex",
			alignItems: "center",
			gap: "8px",
			margin: "14px 0 2px",
			padding: "0 8px"
		} }, React.createElement("span", { style: T.group }, props.title), React.createElement("span", { style: {
			flex: 1,
			height: "1px",
			background: "currentColor",
			opacity: .12
		} }), props.count === void 0 ? null : React.createElement("span", { style: {
			...T.meta,
			fontVariantNumeric: "tabular-nums"
		} }, String(props.count)));
	}
	/** 可滚动的列表容器：固定工具条与脚注，只让内容滚。 */
	function ScrollArea(props) {
		return React.createElement("div", {
			className: "dsh-environment-tray-scroll",
			style: {
				margin: "0 -4px",
				padding: "0 4px"
			}
		}, props.children);
	}
	/** 工具条：搜索 + 刷新 + 计数。固定在列表上方，不参与滚动。 */
	function Toolbar(props) {
		return React.createElement("div", { style: {
			display: "flex",
			alignItems: "center",
			gap: "8px",
			marginBottom: "2px"
		} }, props.children);
	}
	/** 空状态：一句低对比说明，不要插图也不要按钮。 */
	function Empty(props) {
		return React.createElement("p", { style: {
			...T.meta,
			margin: "18px 8px",
			textAlign: "center"
		} }, props.children);
	}
	/** 脚注里的一行说明。 */
	function Note(props) {
		return React.createElement("p", { style: {
			...T.detail,
			margin: "4px 0",
			lineHeight: 1.7
		} }, props.children);
	}
	/** 加载/错误这类整屏状态。 */
	function Placeholder(props) {
		return React.createElement("p", { style: {
			...T.detail,
			margin: "24px 8px",
			textAlign: "center",
			opacity: props.tone === "warn" ? .8 : .5
		} }, props.children);
	}
	//#endregion
	//#region src/client.ts
	const { useState, useEffect, useCallback, useRef } = React;
	const { Button: Button$1, Input: Input$1, Modal: Modal$1 } = Primitives;
	const IconChevronDownOutline14 = Primitives.IconChevronDownOutlineRegular ?? Primitives.IconChevronDownOutline14;
	const EnvironmentIcon = Primitives.IconSlidersTwoOutlineRegular ?? Primitives.IconSettingsOutline16;
	const IconEditOutline16 = Primitives.IconEditOutlineRegular ?? Primitives.IconEditOutline16;
	const IconRefreshOutline16 = Primitives.IconRefreshOutlineRegular ?? Primitives.IconRefreshOutline16;
	const IconSearchOutline16 = Primitives.IconSearchOutlineRegular ?? Primitives.IconSearchOutline16;
	const IconTrashOutline16 = Primitives.IconTrashOutlineRegular ?? Primitives.IconTrashOutline16;
	const STATE_URL = "/api/dsh-environment-tray/state";
	const VALUE_URL = "/api/dsh-environment-tray/value";
	const ENV_WRITE_URL = "/api/dsh-environment-tray/env";
	const ENV_READ_URL = "/api/dsh-environment-tray/env/read";
	const REGISTRY_URL = "/api/dsh-environment-tray/registry";
	const CREDENTIAL_WRITE_URL = "/api/dsh-environment-tray/credentials";
	const WRITABLE_ORDER = [
		"project-env",
		"user-env",
		"os-user",
		"os-machine"
	];
	const CREDENTIAL_HINTS = /(^|_)(API_?KEY|KEY|TOKEN|SECRET|PASSWORD|PASSWD|CREDENTIAL)($|_)/i;
	async function postJson(url, body) {
		const res = await fetch(url, {
			method: "POST",
			headers: { "content-type": "application/json" },
			body: JSON.stringify(body)
		});
		const parsed = await res.json();
		if (res.ok && parsed.ok === true) return parsed;
		throw new ClientError(parsed, res.status);
	}
	async function readValue(name, layer) {
		const result = await postJson(VALUE_URL, {
			name,
			layer
		});
		if (typeof result.value !== "string") throw new ClientError({ error: "read-failed" });
		return result;
	}
	async function readRevision(layer) {
		const result = await postJson(ENV_READ_URL, { layer });
		if (typeof result.revision !== "string") throw new ClientError({ error: "read-failed" });
		return result.revision;
	}
	async function removeValue(name, layer) {
		if (layer.startsWith("os-")) return postJson(REGISTRY_URL, {
			scope: layer,
			name,
			unset: true
		});
		if (layer === "credential") return postJson(CREDENTIAL_WRITE_URL, {
			ref: name,
			unset: true
		});
		return postJson(ENV_WRITE_URL, {
			layer,
			expectedRevision: await readRevision(layer),
			edits: [{
				op: "unset",
				name
			}]
		});
	}
	async function copyValue(value) {
		if (navigator.clipboard?.writeText) {
			await navigator.clipboard.writeText(value);
			return;
		}
		const input = document.createElement("textarea");
		input.setAttribute("data-dsh-environment-tray-copy", "true");
		input.value = value;
		input.style.position = "fixed";
		input.style.opacity = "0";
		document.body.appendChild(input);
		const focused = document.activeElement;
		try {
			input.select();
			if (!document.execCommand("copy")) throw new ClientError({ error: "copy-failed" });
		} finally {
			input.remove();
			focused?.focus();
		}
	}
	function CopyIcon() {
		return React.createElement("svg", {
			width: 16,
			height: 16,
			viewBox: "0 0 24 24",
			fill: "none",
			stroke: "currentColor",
			strokeWidth: 1.6,
			"aria-hidden": true
		}, React.createElement("rect", {
			x: 8,
			y: 8,
			width: 12,
			height: 12,
			rx: 2
		}), React.createElement("path", { d: "M16 8V4H4v12h4" }));
	}
	function CancelIcon() {
		return React.createElement("svg", {
			width: 16,
			height: 16,
			viewBox: "0 0 24 24",
			fill: "none",
			stroke: "currentColor",
			strokeWidth: 1.6,
			"aria-hidden": true
		}, React.createElement("path", { d: "m6 6 12 12M18 6 6 18" }));
	}
	function DraftValue(props) {
		const { edit, name, sensitive, t } = props;
		const [copyError, setCopyError] = useState(null);
		const multiline = /[\r\n]/.test(edit.draft);
		const masked = sensitive && !edit.visible;
		return React.createElement("span", {
			className: "dsh-environment-tray-valuecell dsh-environment-tray-value",
			style: { fontSize: T.value.fontSize }
		}, React.createElement(multiline && !masked ? "textarea" : "input", {
			className: "dsh-environment-tray-input",
			"aria-label": t("valueLabel", { name }),
			"aria-invalid": edit.error !== null,
			value: edit.draft,
			autoFocus: true,
			type: masked ? "password" : "text",
			rows: multiline ? Math.min(4, edit.draft.split(/\r\n|\r|\n/).length) : void 0,
			title: t(multiline && masked ? "multilineHint" : "editHint"),
			readOnly: !edit.ready || edit.busy || multiline && masked,
			"aria-busy": edit.busy,
			placeholder: edit.ready ? "" : t("loading"),
			onChange: (e) => edit.setDraft(e.target.value),
			onKeyDown: edit.onKeyDown
		}), sensitive ? React.createElement(Button$1, {
			variant: "ghost",
			size: "sm",
			icon: React.createElement(EyeIcon, { hidden: edit.visible }),
			"aria-label": t(edit.visible ? "hideInput" : "showInput"),
			title: t(edit.visible ? "hideInput" : "showInput"),
			disabled: !edit.ready || edit.busy,
			onClick: () => edit.setVisible(!edit.visible)
		}) : React.createElement("span", null), React.createElement(Button$1, {
			variant: "ghost",
			size: "sm",
			icon: React.createElement(CopyIcon),
			"aria-label": t("copyValue"),
			title: t("copyValue"),
			disabled: !edit.ready || edit.busy,
			onClick: async () => {
				setCopyError(null);
				try {
					await copyValue(edit.draft);
				} catch (error) {
					setCopyError(error);
				}
			}
		}), edit.error !== null || copyError !== null ? React.createElement("span", {
			className: "dsh-environment-tray-value-error",
			role: "alert",
			style: T.meta
		}, errorLabel(t, edit.error ?? copyError)) : null);
	}
	/** Each value owns its temporary visibility; hiding discards the fetched plaintext. */
	function ValueCell(props) {
		const { t } = props;
		const maskedByDefault = props.sensitive === true || props.layer.redacted === true;
		const [visible, setVisible] = useState(!maskedByDefault);
		const [fullValue, setFullValue] = useState(null);
		const [busy, setBusy] = useState(false);
		const [copied, setCopied] = useState(false);
		const [error, setError] = useState(null);
		const generation = useRef(0);
		useEffect(() => () => {
			generation.current += 1;
		}, []);
		const toggle = async () => {
			setError(null);
			setCopied(false);
			if (visible) {
				generation.current += 1;
				setVisible(false);
				setFullValue(null);
				return;
			}
			const request = ++generation.current;
			setBusy(true);
			try {
				const result = await readValue(props.name, props.layer.layer);
				if (request !== generation.current) return;
				setFullValue(result.value);
				setVisible(true);
			} catch (error) {
				if (request === generation.current) setError(error);
			} finally {
				if (request === generation.current) setBusy(false);
			}
		};
		const copy = async () => {
			const request = ++generation.current;
			setBusy(true);
			setError(null);
			try {
				const value = fullValue ?? (await readValue(props.name, props.layer.layer)).value;
				if (request !== generation.current) return;
				await copyValue(value);
				if (request === generation.current) setCopied(true);
			} catch (error) {
				if (request === generation.current) setError(error);
			} finally {
				if (request === generation.current) setBusy(false);
			}
		};
		const text = visible ? fullValue ?? props.layer.valueSummary?.preview ?? "—" : null;
		return React.createElement("span", {
			className: "dsh-environment-tray-valuecell dsh-environment-tray-value",
			style: { fontSize: T.value.fontSize }
		}, React.createElement(Value, {
			masked: !visible,
			expanded: fullValue !== null,
			title: visible ? text ?? void 0 : void 0
		}, text), React.createElement(Button$1, {
			variant: "ghost",
			size: "sm",
			icon: React.createElement(EyeIcon, { hidden: visible }),
			title: t(visible ? "hideValue" : "showValue"),
			"aria-label": t(visible ? "hideValue" : "showValue"),
			"aria-pressed": visible,
			disabled: busy,
			onClick: toggle
		}), React.createElement(Button$1, {
			variant: "ghost",
			size: "sm",
			icon: React.createElement(CopyIcon),
			title: t(copied ? "copied" : "copyValue"),
			"aria-label": t(copied ? "copied" : "copyValue"),
			disabled: busy,
			onClick: copy
		}), error === null ? null : React.createElement("span", {
			role: "alert",
			style: T.meta
		}, errorLabel(t, error)));
	}
	function EditActions(props) {
		const { edit, t } = props;
		return React.createElement(RowActions, null, React.createElement("span", null, edit.editing ? React.createElement(Button$1, {
			variant: "ghost",
			size: "sm",
			icon: React.createElement(CancelIcon),
			title: t("cancelEdit"),
			"aria-label": t("cancelEdit"),
			disabled: edit.busy && edit.ready,
			onClick: edit.cancel
		}) : props.available ? React.createElement(Button$1, {
			variant: "ghost",
			size: "sm",
			icon: React.createElement(IconEditOutline16),
			title: props.label ?? t("edit"),
			"aria-label": props.label ?? t("edit"),
			onClick: edit.begin
		}) : null), React.createElement("span", null, props.remove), React.createElement("span", null, props.extra));
	}
	function VariableRow(props) {
		const { variable, state, version, expanded, onToggle, onSaved, onDeleted, t } = props;
		const effective = variable.layers.find((l) => l.layer === variable.effective);
		const target = variable.layers.find((l) => l.writable && WRITABLE_ORDER.includes(l.layer));
		const edit = useInlineEdit({
			read: target ? () => readValue(variable.name, target.layer) : void 0,
			write: async (value, revision) => {
				if (!target) throw new ClientError({ error: "not-editable" });
				if (target.layer.startsWith("os-")) return postJson(REGISTRY_URL, {
					scope: target.layer,
					name: variable.name,
					value,
					type: target.registryType ?? "REG_SZ"
				});
				if (revision === void 0) throw new ClientError({ error: "reopen-editor" });
				return postJson(ENV_WRITE_URL, {
					layer: target.layer,
					expectedRevision: revision,
					edits: [{
						op: "set",
						name: variable.name,
						value
					}]
				});
			},
			onSaved
		});
		return React.createElement("div", null, React.createElement(Row, {
			active: edit.editing || expanded,
			onBlur: edit.editing ? edit.onBlur : void 0
		}, React.createElement(Key, { title: variable.name }, variable.name), edit.editing ? React.createElement(DraftValue, {
			t,
			edit,
			name: variable.name,
			sensitive: variable.sensitive
		}) : effective ? React.createElement(ValueCell, {
			t,
			key: version,
			name: variable.name,
			layer: effective,
			sensitive: variable.sensitive
		}) : React.createElement(Value, null, "—"), React.createElement("span", { className: "dsh-environment-tray-row-meta" }, React.createElement(Meta, { parts: edit.editing ? [edit.busy ? t(edit.ready ? "saving" : "loading") : layerLabel(t, target.layer)] : [layerLabel(t, variable.effective), variable.shadowed ? t("layerCount", { count: variable.layers.length }) : null] }), React.createElement(EditActions, {
			t,
			edit,
			available: !!target,
			remove: target ? React.createElement(DeleteAction, {
				t,
				key: target.layer,
				name: variable.name,
				layer: target.layer,
				fallback: variable.layers.length > 1,
				icon: React.createElement(IconTrashOutline16),
				disabled: edit.busy && edit.ready,
				onOpen: edit.pause,
				onClose: edit.resume,
				remove: async () => {
					const result = await removeValue(variable.name, target.layer);
					edit.cancel();
					if (result.undo) onDeleted({
						...result.undo,
						scope: target.layer
					});
					onSaved(result);
				}
			}) : null,
			extra: variable.shadowed ? React.createElement(Button$1, {
				variant: "ghost",
				size: "sm",
				icon: React.createElement(IconChevronDownOutline14),
				title: t(expanded ? "collapseLayers" : "expandLayers"),
				"aria-label": t(expanded ? "collapseLayers" : "expandLayers"),
				onClick: () => onToggle(variable.name)
			}) : null
		}))), expanded ? React.createElement("div", { className: "dsh-environment-tray-layers" }, variable.layers.map((layer) => React.createElement(Row, { key: layer.layer }, React.createElement(Key, { title: layer.path }, layerLabel(t, layer.layer)), React.createElement(ValueCell, {
			t,
			key: version,
			name: variable.name,
			layer,
			sensitive: variable.sensitive
		}), React.createElement("span", { className: "dsh-environment-tray-row-meta" }, React.createElement("span", {
			style: T.meta,
			title: layer.blockedCode ? reasonLabel(t, layer.blockedCode, state.blockedReasonText?.[layer.blockedCode]) : layer.path
		}, layer.layer === variable.effective ? t("current") : null), React.createElement(RowActions))))) : null);
	}
	function CredentialRow(props) {
		const { name, info, version, onSaved, t } = props;
		const edit = useInlineEdit({
			read: info.editable ? () => info.configured ? readValue(name, "credential") : Promise.resolve({ value: "" }) : void 0,
			write: (value) => postJson(CREDENTIAL_WRITE_URL, {
				ref: name,
				value
			}),
			onSaved
		});
		return React.createElement(Row, {
			active: edit.editing,
			onBlur: edit.editing ? edit.onBlur : void 0
		}, React.createElement(Key, null, name), edit.editing ? React.createElement(DraftValue, {
			t,
			edit,
			name,
			sensitive: true
		}) : info.configured ? React.createElement(ValueCell, {
			t,
			key: version,
			name,
			layer: {
				layer: "credential",
				redacted: true
			},
			sensitive: true
		}) : React.createElement(Value, null, "—"), React.createElement("span", { className: "dsh-environment-tray-row-meta" }, React.createElement(Meta, { parts: [edit.editing ? edit.busy ? t(edit.ready ? "saving" : "loading") : t("layer.file") : info.configured ? info.source ? layerLabel(t, info.source) : info.sourceLabel : t("unset")] }), React.createElement(EditActions, {
			t,
			edit,
			available: !!info.editable,
			remove: info.configured && info.editable ? React.createElement(DeleteAction, {
				t,
				name,
				layer: "credential",
				icon: React.createElement(IconTrashOutline16),
				disabled: edit.busy && edit.ready,
				onOpen: edit.pause,
				onClose: edit.resume,
				remove: async () => {
					await removeValue(name, "credential");
					edit.cancel();
					onSaved();
				}
			}) : null,
			label: t(info.configured ? "replace" : "set")
		})));
	}
	function CredentialPanel(props) {
		const { t } = props;
		const [status, setStatus] = useState(null);
		const [error, setError] = useState(null);
		const key = props.names.join(",");
		useEffect(() => {
			let active = true;
			if (!key) {
				setStatus({});
				return;
			}
			fetch("/api/dsh-environment-tray/credential-state?refs=" + encodeURIComponent(key)).then(async (res) => {
				if (!res.ok) throw new Error(`HTTP ${res.status}`);
				return res.json();
			}).then((body) => {
				if (active) setStatus(body.available === true ? body.refs ?? {} : {});
			}).catch((error) => {
				if (active) setError(error);
			});
			return () => {
				active = false;
			};
		}, [key, props.version]);
		if (!props.names.length) return null;
		return React.createElement(React.Fragment, null, React.createElement(GroupHeading, {
			title: t("layer.credential"),
			count: props.names.length
		}), error !== null ? React.createElement(Note, null, t("readError", { error: errorLabel(t, error) })) : null, status === null ? React.createElement(Empty, null, t("loading")) : props.names.map((name) => React.createElement(CredentialRow, {
			t,
			key: name,
			name,
			info: status[name] ?? {},
			version: props.version,
			onSaved: props.onSaved
		})));
	}
	function EnvManagerPanel({ t }) {
		const [state, setState] = useState(null);
		const [version, setVersion] = useState(0);
		const [error, setError] = useState(null);
		const [expanded, setExpanded] = useState({});
		const [filter, setFilter] = useState("");
		const [adding, setAdding] = useState(false);
		const [undo, setUndo] = useState(null);
		const [undoBusy, setUndoBusy] = useState(false);
		const [restartNeeded, setRestartNeeded] = useState(false);
		const generation = useRef(0);
		const load = useCallback(async () => {
			const request = ++generation.current;
			setError(null);
			try {
				const res = await fetch(STATE_URL);
				if (!res.ok) throw new Error(`HTTP ${res.status}`);
				const body = await res.json();
				if (request !== generation.current) return;
				setState(body);
				setVersion((version) => version + 1);
			} catch (error) {
				if (request === generation.current) setError(error);
			}
		}, []);
		useEffect(() => {
			load();
			return () => {
				generation.current += 1;
			};
		}, [load]);
		const onSaved = (result) => {
			if (result?.restartRequired) setRestartNeeded(true);
			load();
		};
		const create = async (layer, name, value) => {
			const result = layer.startsWith("os-") ? await postJson(REGISTRY_URL, {
				scope: layer,
				name,
				value,
				type: "REG_SZ",
				createOnly: true
			}) : await postJson(ENV_WRITE_URL, {
				layer,
				expectedRevision: await readRevision(layer),
				createOnly: true,
				edits: [{
					op: "set",
					name,
					value
				}]
			});
			setAdding(false);
			if (!name.toUpperCase().includes(filter.trim().toUpperCase())) setFilter("");
			onSaved(result);
		};
		const toggle = (name) => setExpanded((prev) => ({
			...prev,
			[name]: !prev[name]
		}));
		const undoRemove = async () => {
			if (!undo) return;
			setUndoBusy(true);
			try {
				const result = await postJson(REGISTRY_URL, {
					scope: undo.scope,
					name: undo.name,
					value: undo.value,
					type: undo.type
				});
				setUndo(null);
				onSaved(result);
			} catch (error) {
				setError(error);
			} finally {
				setUndoBusy(false);
			}
		};
		if (!state) return error !== null ? React.createElement(React.Fragment, null, React.createElement(Placeholder, null, t("readError", { error: errorLabel(t, error) })), React.createElement(Button$1, { onClick: load }, t("retry"))) : React.createElement(Placeholder, null, t("loadingEnvironment"));
		const variables = state.variables ?? [];
		const needle = filter.trim().toUpperCase();
		const shown = variables.filter((v) => v.name.toUpperCase().includes(needle));
		const headings = [
			["runtime", t("group.runtime")],
			["project-env", t("layer.project")],
			["user-env", t("layer.user")],
			["credential", t("group.credential")],
			["os-user", t("layer.osUser")],
			["os-machine", t("layer.osMachine")],
			["readonly", t("group.readonly")]
		];
		const groupOf = (v) => v.runtimeManaged ? "runtime" : v.effective === "credential" ? "credential" : WRITABLE_ORDER.find((key) => v.layers.some((l) => l.layer === key && l.writable)) ?? (WRITABLE_ORDER.includes(v.effective) ? v.effective : "readonly");
		const credentialNames = shown.filter((v) => CREDENTIAL_HINTS.test(v.name)).map((v) => v.name).sort();
		const rows = [];
		for (const [key, title] of headings) {
			const items = shown.filter((v) => groupOf(v) === key).sort((a, b) => a.name.localeCompare(b.name, "en", { numeric: true }));
			if (items.length) rows.push(React.createElement(GroupHeading, {
				key: "h-" + key,
				title,
				count: items.length
			}), ...items.map((variable) => React.createElement(VariableRow, {
				t,
				key: variable.name,
				variable,
				state,
				version,
				expanded: expanded[variable.name] === true,
				onToggle: toggle,
				onSaved,
				onDeleted: setUndo
			})));
			if (key === "credential") rows.push(React.createElement(CredentialPanel, {
				t,
				key: "credentials",
				names: credentialNames,
				onSaved,
				version
			}));
		}
		return React.createElement(React.Fragment, null, React.createElement(Toolbar, null, React.createElement(Input$1, {
			icon: React.createElement(IconSearchOutline16),
			placeholder: t("search"),
			value: filter,
			style: {
				flex: 1,
				fontSize: 12
			},
			onChange: (e) => setFilter(e.target.value)
		}), React.createElement(Button$1, {
			variant: "ghost",
			size: "sm",
			icon: React.createElement(IconRefreshOutline16),
			title: t("refresh"),
			"aria-label": t("refresh"),
			onClick: load
		}), React.createElement(NewVariableButton, {
			t,
			onClick: () => setAdding(true)
		}), React.createElement("span", { style: T.meta }, needle ? `${shown.length} / ${variables.length}` : String(variables.length))), adding ? React.createElement(NewVariableForm, {
			t,
			create,
			onCancel: () => setAdding(false),
			layers: [
				"user-env",
				"project-env",
				...state.os?.supported === true ? ["os-user", "os-machine"].filter((layer) => !state.os?.scopes?.[layer]?.error) : []
			]
		}) : null, error !== null ? React.createElement(Note, null, t("readError", { error: errorLabel(t, error) })) : null, restartNeeded ? React.createElement(Note, null, t("restart")) : null, undo ? React.createElement("div", { className: "dsh-environment-tray-editor" }, React.createElement("span", { style: T.meta }, t("deleted", { name: undo.name })), React.createElement(Button$1, {
			variant: "ghost",
			size: "sm",
			disabled: undoBusy,
			onClick: undoRemove
		}, t("undoDelete"))) : null, state.warnings?.map((warning, i) => React.createElement(Note, { key: i }, warning.code === "bom" ? t("warning.bom", { path: warning.path ?? ".env" }) : warning.message)), Object.entries(state.os?.scopes ?? {}).filter(([, scope]) => scope.error).map(([key]) => React.createElement(Note, { key }, t("scopeReadError", { scope: layerLabel(t, key) }))), React.createElement(ScrollArea, null, rows, shown.length ? null : React.createElement(Empty, null, t("noMatches"))));
	}
	function EnvManagerAction({ t }) {
		const [open, setOpen] = useState(false);
		return React.createElement(React.Fragment, null, React.createElement("span", { className: "dsh-environment-tray-entry" }, React.createElement(Button$1, {
			variant: "ghost",
			size: "sm",
			icon: React.createElement(EnvironmentIcon),
			title: t("title"),
			"aria-label": t("title"),
			onClick: () => setOpen(true)
		})), React.createElement(Modal$1, {
			open,
			onClose: () => setOpen(false),
			title: t("title"),
			closeLabel: t("close"),
			className: "dsh-environment-tray-dialog"
		}, open ? React.createElement(EnvManagerPanel, { t }) : null));
	}
	const inject = ["slots", "locale"];
	function apply(ctx) {
		installClientStyles();
		ctx.effect(() => ctx.locale.register(LOCALE_NS, dictionaries), "dsh-environment-tray: browser dictionaries");
		ctx.slots.inject("conversation.header.leading", () => ctx.slots.register({
			name: "conversation.header.leading",
			locale: LOCALE_NS
		}, EnvManagerAction));
	}
	//#endregion

	exports.EnvManagerAction = EnvManagerAction;
	exports.EnvManagerPanel = EnvManagerPanel;
	exports.apply = apply;
	exports.inject = inject;
	return module.exports
	}
})
